// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.15.8
// source: service_accounts.proto

package service_accounts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceAccounts_CreateServiceAccount_FullMethodName          = "/Superplane.ServiceAccounts.ServiceAccounts/CreateServiceAccount"
	ServiceAccounts_ListServiceAccounts_FullMethodName           = "/Superplane.ServiceAccounts.ServiceAccounts/ListServiceAccounts"
	ServiceAccounts_DescribeServiceAccount_FullMethodName        = "/Superplane.ServiceAccounts.ServiceAccounts/DescribeServiceAccount"
	ServiceAccounts_UpdateServiceAccount_FullMethodName          = "/Superplane.ServiceAccounts.ServiceAccounts/UpdateServiceAccount"
	ServiceAccounts_DeleteServiceAccount_FullMethodName          = "/Superplane.ServiceAccounts.ServiceAccounts/DeleteServiceAccount"
	ServiceAccounts_RegenerateServiceAccountToken_FullMethodName = "/Superplane.ServiceAccounts.ServiceAccounts/RegenerateServiceAccountToken"
)

// ServiceAccountsClient is the client API for ServiceAccounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceAccountsClient interface {
	CreateServiceAccount(ctx context.Context, in *CreateServiceAccountRequest, opts ...grpc.CallOption) (*CreateServiceAccountResponse, error)
	ListServiceAccounts(ctx context.Context, in *ListServiceAccountsRequest, opts ...grpc.CallOption) (*ListServiceAccountsResponse, error)
	DescribeServiceAccount(ctx context.Context, in *DescribeServiceAccountRequest, opts ...grpc.CallOption) (*DescribeServiceAccountResponse, error)
	UpdateServiceAccount(ctx context.Context, in *UpdateServiceAccountRequest, opts ...grpc.CallOption) (*UpdateServiceAccountResponse, error)
	DeleteServiceAccount(ctx context.Context, in *DeleteServiceAccountRequest, opts ...grpc.CallOption) (*DeleteServiceAccountResponse, error)
	RegenerateServiceAccountToken(ctx context.Context, in *RegenerateServiceAccountTokenRequest, opts ...grpc.CallOption) (*RegenerateServiceAccountTokenResponse, error)
}

type serviceAccountsClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceAccountsClient(cc grpc.ClientConnInterface) ServiceAccountsClient {
	return &serviceAccountsClient{cc}
}

func (c *serviceAccountsClient) CreateServiceAccount(ctx context.Context, in *CreateServiceAccountRequest, opts ...grpc.CallOption) (*CreateServiceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceAccountResponse)
	err := c.cc.Invoke(ctx, ServiceAccounts_CreateServiceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountsClient) ListServiceAccounts(ctx context.Context, in *ListServiceAccountsRequest, opts ...grpc.CallOption) (*ListServiceAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceAccountsResponse)
	err := c.cc.Invoke(ctx, ServiceAccounts_ListServiceAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountsClient) DescribeServiceAccount(ctx context.Context, in *DescribeServiceAccountRequest, opts ...grpc.CallOption) (*DescribeServiceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeServiceAccountResponse)
	err := c.cc.Invoke(ctx, ServiceAccounts_DescribeServiceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountsClient) UpdateServiceAccount(ctx context.Context, in *UpdateServiceAccountRequest, opts ...grpc.CallOption) (*UpdateServiceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServiceAccountResponse)
	err := c.cc.Invoke(ctx, ServiceAccounts_UpdateServiceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountsClient) DeleteServiceAccount(ctx context.Context, in *DeleteServiceAccountRequest, opts ...grpc.CallOption) (*DeleteServiceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServiceAccountResponse)
	err := c.cc.Invoke(ctx, ServiceAccounts_DeleteServiceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountsClient) RegenerateServiceAccountToken(ctx context.Context, in *RegenerateServiceAccountTokenRequest, opts ...grpc.CallOption) (*RegenerateServiceAccountTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateServiceAccountTokenResponse)
	err := c.cc.Invoke(ctx, ServiceAccounts_RegenerateServiceAccountToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceAccountsServer is the server API for ServiceAccounts service.
// All implementations should embed UnimplementedServiceAccountsServer
// for forward compatibility.
type ServiceAccountsServer interface {
	CreateServiceAccount(context.Context, *CreateServiceAccountRequest) (*CreateServiceAccountResponse, error)
	ListServiceAccounts(context.Context, *ListServiceAccountsRequest) (*ListServiceAccountsResponse, error)
	DescribeServiceAccount(context.Context, *DescribeServiceAccountRequest) (*DescribeServiceAccountResponse, error)
	UpdateServiceAccount(context.Context, *UpdateServiceAccountRequest) (*UpdateServiceAccountResponse, error)
	DeleteServiceAccount(context.Context, *DeleteServiceAccountRequest) (*DeleteServiceAccountResponse, error)
	RegenerateServiceAccountToken(context.Context, *RegenerateServiceAccountTokenRequest) (*RegenerateServiceAccountTokenResponse, error)
}

// UnimplementedServiceAccountsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceAccountsServer struct{}

func (UnimplementedServiceAccountsServer) CreateServiceAccount(context.Context, *CreateServiceAccountRequest) (*CreateServiceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServiceAccount not implemented")
}
func (UnimplementedServiceAccountsServer) ListServiceAccounts(context.Context, *ListServiceAccountsRequest) (*ListServiceAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceAccounts not implemented")
}
func (UnimplementedServiceAccountsServer) DescribeServiceAccount(context.Context, *DescribeServiceAccountRequest) (*DescribeServiceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeServiceAccount not implemented")
}
func (UnimplementedServiceAccountsServer) UpdateServiceAccount(context.Context, *UpdateServiceAccountRequest) (*UpdateServiceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateServiceAccount not implemented")
}
func (UnimplementedServiceAccountsServer) DeleteServiceAccount(context.Context, *DeleteServiceAccountRequest) (*DeleteServiceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteServiceAccount not implemented")
}
func (UnimplementedServiceAccountsServer) RegenerateServiceAccountToken(context.Context, *RegenerateServiceAccountTokenRequest) (*RegenerateServiceAccountTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegenerateServiceAccountToken not implemented")
}
func (UnimplementedServiceAccountsServer) testEmbeddedByValue() {}

// UnsafeServiceAccountsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceAccountsServer will
// result in compilation errors.
type UnsafeServiceAccountsServer interface {
	mustEmbedUnimplementedServiceAccountsServer()
}

func RegisterServiceAccountsServer(s grpc.ServiceRegistrar, srv ServiceAccountsServer) {
	// If the following call panics, it indicates UnimplementedServiceAccountsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceAccounts_ServiceDesc, srv)
}

func _ServiceAccounts_CreateServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountsServer).CreateServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccounts_CreateServiceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountsServer).CreateServiceAccount(ctx, req.(*CreateServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccounts_ListServiceAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountsServer).ListServiceAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccounts_ListServiceAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountsServer).ListServiceAccounts(ctx, req.(*ListServiceAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccounts_DescribeServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountsServer).DescribeServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccounts_DescribeServiceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountsServer).DescribeServiceAccount(ctx, req.(*DescribeServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccounts_UpdateServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountsServer).UpdateServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccounts_UpdateServiceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountsServer).UpdateServiceAccount(ctx, req.(*UpdateServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccounts_DeleteServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountsServer).DeleteServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccounts_DeleteServiceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountsServer).DeleteServiceAccount(ctx, req.(*DeleteServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccounts_RegenerateServiceAccountToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateServiceAccountTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountsServer).RegenerateServiceAccountToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccounts_RegenerateServiceAccountToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountsServer).RegenerateServiceAccountToken(ctx, req.(*RegenerateServiceAccountTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceAccounts_ServiceDesc is the grpc.ServiceDesc for ServiceAccounts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceAccounts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Superplane.ServiceAccounts.ServiceAccounts",
	HandlerType: (*ServiceAccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServiceAccount",
			Handler:    _ServiceAccounts_CreateServiceAccount_Handler,
		},
		{
			MethodName: "ListServiceAccounts",
			Handler:    _ServiceAccounts_ListServiceAccounts_Handler,
		},
		{
			MethodName: "DescribeServiceAccount",
			Handler:    _ServiceAccounts_DescribeServiceAccount_Handler,
		},
		{
			MethodName: "UpdateServiceAccount",
			Handler:    _ServiceAccounts_UpdateServiceAccount_Handler,
		},
		{
			MethodName: "DeleteServiceAccount",
			Handler:    _ServiceAccounts_DeleteServiceAccount_Handler,
		},
		{
			MethodName: "RegenerateServiceAccountToken",
			Handler:    _ServiceAccounts_RegenerateServiceAccountToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_accounts.proto",
}
