// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: service_accounts.proto

package service_accounts

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceAccount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OrganizationId string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	HasToken       bool                   `protobuf:"varint,6,opt,name=has_token,json=hasToken,proto3" json:"has_token,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceAccount) Reset() {
	*x = ServiceAccount{}
	mi := &file_service_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccount) ProtoMessage() {}

func (x *ServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccount.ProtoReflect.Descriptor instead.
func (*ServiceAccount) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceAccount) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ServiceAccount) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ServiceAccount) GetHasToken() bool {
	if x != nil {
		return x.HasToken
	}
	return false
}

func (x *ServiceAccount) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceAccount) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateServiceAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceAccountRequest) Reset() {
	*x = CreateServiceAccountRequest{}
	mi := &file_service_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountRequest) ProtoMessage() {}

func (x *CreateServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServiceAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateServiceAccountRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateServiceAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount *ServiceAccount        `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateServiceAccountResponse) Reset() {
	*x = CreateServiceAccountResponse{}
	mi := &file_service_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountResponse) ProtoMessage() {}

func (x *CreateServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *CreateServiceAccountResponse) GetServiceAccount() *ServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *CreateServiceAccountResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListServiceAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceAccountsRequest) Reset() {
	*x = ListServiceAccountsRequest{}
	mi := &file_service_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountsRequest) ProtoMessage() {}

func (x *ListServiceAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListServiceAccountsRequest) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{3}
}

type ListServiceAccountsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccounts []*ServiceAccount      `protobuf:"bytes,1,rep,name=service_accounts,json=serviceAccounts,proto3" json:"service_accounts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListServiceAccountsResponse) Reset() {
	*x = ListServiceAccountsResponse{}
	mi := &file_service_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountsResponse) ProtoMessage() {}

func (x *ListServiceAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListServiceAccountsResponse) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *ListServiceAccountsResponse) GetServiceAccounts() []*ServiceAccount {
	if x != nil {
		return x.ServiceAccounts
	}
	return nil
}

type DescribeServiceAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeServiceAccountRequest) Reset() {
	*x = DescribeServiceAccountRequest{}
	mi := &file_service_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeServiceAccountRequest) ProtoMessage() {}

func (x *DescribeServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*DescribeServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeServiceAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DescribeServiceAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount *ServiceAccount        `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeServiceAccountResponse) Reset() {
	*x = DescribeServiceAccountResponse{}
	mi := &file_service_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeServiceAccountResponse) ProtoMessage() {}

func (x *DescribeServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*DescribeServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeServiceAccountResponse) GetServiceAccount() *ServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

type UpdateServiceAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceAccountRequest) Reset() {
	*x = UpdateServiceAccountRequest{}
	mi := &file_service_accounts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceAccountRequest) ProtoMessage() {}

func (x *UpdateServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateServiceAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateServiceAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateServiceAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount *ServiceAccount        `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateServiceAccountResponse) Reset() {
	*x = UpdateServiceAccountResponse{}
	mi := &file_service_accounts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceAccountResponse) ProtoMessage() {}

func (x *UpdateServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateServiceAccountResponse) GetServiceAccount() *ServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

type DeleteServiceAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceAccountRequest) Reset() {
	*x = DeleteServiceAccountRequest{}
	mi := &file_service_accounts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceAccountRequest) ProtoMessage() {}

func (x *DeleteServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteServiceAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteServiceAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceAccountResponse) Reset() {
	*x = DeleteServiceAccountResponse{}
	mi := &file_service_accounts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceAccountResponse) ProtoMessage() {}

func (x *DeleteServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{10}
}

type RegenerateServiceAccountTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateServiceAccountTokenRequest) Reset() {
	*x = RegenerateServiceAccountTokenRequest{}
	mi := &file_service_accounts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateServiceAccountTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateServiceAccountTokenRequest) ProtoMessage() {}

func (x *RegenerateServiceAccountTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateServiceAccountTokenRequest.ProtoReflect.Descriptor instead.
func (*RegenerateServiceAccountTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{11}
}

func (x *RegenerateServiceAccountTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegenerateServiceAccountTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateServiceAccountTokenResponse) Reset() {
	*x = RegenerateServiceAccountTokenResponse{}
	mi := &file_service_accounts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateServiceAccountTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateServiceAccountTokenResponse) ProtoMessage() {}

func (x *RegenerateServiceAccountTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_accounts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateServiceAccountTokenResponse.ProtoReflect.Descriptor instead.
func (*RegenerateServiceAccountTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_accounts_proto_rawDescGZIP(), []int{12}
}

func (x *RegenerateServiceAccountTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_service_accounts_proto protoreflect.FileDescriptor

const file_service_accounts_proto_rawDesc = "" +
	"\n" +
	"\x16service_accounts.proto\x12\x1aSuperplane.ServiceAccounts\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb1\x02\n" +
	"\x0eServiceAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x1b\n" +
	"\thas_token\x18\x06 \x01(\bR\bhasToken\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"g\n" +
	"\x1bCreateServiceAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\x89\x01\n" +
	"\x1cCreateServiceAccountResponse\x12S\n" +
	"\x0fservice_account\x18\x01 \x01(\v2*.Superplane.ServiceAccounts.ServiceAccountR\x0eserviceAccount\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x1c\n" +
	"\x1aListServiceAccountsRequest\"t\n" +
	"\x1bListServiceAccountsResponse\x12U\n" +
	"\x10service_accounts\x18\x01 \x03(\v2*.Superplane.ServiceAccounts.ServiceAccountR\x0fserviceAccounts\"/\n" +
	"\x1dDescribeServiceAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	"\x1eDescribeServiceAccountResponse\x12S\n" +
	"\x0fservice_account\x18\x01 \x01(\v2*.Superplane.ServiceAccounts.ServiceAccountR\x0eserviceAccount\"c\n" +
	"\x1bUpdateServiceAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"s\n" +
	"\x1cUpdateServiceAccountResponse\x12S\n" +
	"\x0fservice_account\x18\x01 \x01(\v2*.Superplane.ServiceAccounts.ServiceAccountR\x0eserviceAccount\"-\n" +
	"\x1bDeleteServiceAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\x1cDeleteServiceAccountResponse\"6\n" +
	"$RegenerateServiceAccountTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"%RegenerateServiceAccountTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xba\r\n" +
	"\x0fServiceAccounts\x12\x90\x02\n" +
	"\x14CreateServiceAccount\x127.Superplane.ServiceAccounts.CreateServiceAccountRequest\x1a8.Superplane.ServiceAccounts.CreateServiceAccountResponse\"\x84\x01\x92A^\n" +
	"\x0fServiceAccounts\x12\x18Create a service account\x1a1Creates a new service account in the organization\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/service-accounts\x12\x85\x02\n" +
	"\x13ListServiceAccounts\x126.Superplane.ServiceAccounts.ListServiceAccountsRequest\x1a7.Superplane.ServiceAccounts.ListServiceAccountsResponse\"}\x92AZ\n" +
	"\x0fServiceAccounts\x12\x15List service accounts\x1a0Returns all service accounts in the organization\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/service-accounts\x12\x96\x02\n" +
	"\x16DescribeServiceAccount\x129.Superplane.ServiceAccounts.DescribeServiceAccountRequest\x1a:.Superplane.ServiceAccounts.DescribeServiceAccountResponse\"\x84\x01\x92A\\\n" +
	"\x0fServiceAccounts\x12\x1aDescribe a service account\x1a-Returns details of a specific service account\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/service-accounts/{id}\x12\x98\x02\n" +
	"\x14UpdateServiceAccount\x127.Superplane.ServiceAccounts.UpdateServiceAccountRequest\x1a8.Superplane.ServiceAccounts.UpdateServiceAccountResponse\"\x8c\x01\x92Aa\n" +
	"\x0fServiceAccounts\x12\x18Update a service account\x1a4Updates the name or description of a service account\x82\xd3\xe4\x93\x02\":\x01*2\x1d/api/v1/service-accounts/{id}\x12\x98\x02\n" +
	"\x14DeleteServiceAccount\x127.Superplane.ServiceAccounts.DeleteServiceAccountRequest\x1a8.Superplane.ServiceAccounts.DeleteServiceAccountResponse\"\x8c\x01\x92Ad\n" +
	"\x0fServiceAccounts\x12\x18Delete a service account\x1a7Deletes a service account and removes its RBAC policies\x82\xd3\xe4\x93\x02\x1f*\x1d/api/v1/service-accounts/{id}\x12\xbc\x02\n" +
	"\x1dRegenerateServiceAccountToken\x12@.Superplane.ServiceAccounts.RegenerateServiceAccountTokenRequest\x1aA.Superplane.ServiceAccounts.RegenerateServiceAccountTokenResponse\"\x95\x01\x92Ad\n" +
	"\x0fServiceAccounts\x12 Regenerate service account token\x1a/Regenerates the API token for a service account\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/service-accounts/{id}/tokenB\xe0\x01\x92A\x9c\x01\x12r\n" +
	"\x1fSuperplane Service Accounts API\x12#API for Superplane Service Accounts\"%\n" +
	"\vAPI Support\x1a\x16support@superplane.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ>github.com/superplanehq/superplane/pkg/protos/service_accountsb\x06proto3"

var (
	file_service_accounts_proto_rawDescOnce sync.Once
	file_service_accounts_proto_rawDescData []byte
)

func file_service_accounts_proto_rawDescGZIP() []byte {
	file_service_accounts_proto_rawDescOnce.Do(func() {
		file_service_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_accounts_proto_rawDesc), len(file_service_accounts_proto_rawDesc)))
	})
	return file_service_accounts_proto_rawDescData
}

var file_service_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_service_accounts_proto_goTypes = []any{
	(*ServiceAccount)(nil),                        // 0: Superplane.ServiceAccounts.ServiceAccount
	(*CreateServiceAccountRequest)(nil),           // 1: Superplane.ServiceAccounts.CreateServiceAccountRequest
	(*CreateServiceAccountResponse)(nil),          // 2: Superplane.ServiceAccounts.CreateServiceAccountResponse
	(*ListServiceAccountsRequest)(nil),            // 3: Superplane.ServiceAccounts.ListServiceAccountsRequest
	(*ListServiceAccountsResponse)(nil),           // 4: Superplane.ServiceAccounts.ListServiceAccountsResponse
	(*DescribeServiceAccountRequest)(nil),         // 5: Superplane.ServiceAccounts.DescribeServiceAccountRequest
	(*DescribeServiceAccountResponse)(nil),        // 6: Superplane.ServiceAccounts.DescribeServiceAccountResponse
	(*UpdateServiceAccountRequest)(nil),           // 7: Superplane.ServiceAccounts.UpdateServiceAccountRequest
	(*UpdateServiceAccountResponse)(nil),          // 8: Superplane.ServiceAccounts.UpdateServiceAccountResponse
	(*DeleteServiceAccountRequest)(nil),           // 9: Superplane.ServiceAccounts.DeleteServiceAccountRequest
	(*DeleteServiceAccountResponse)(nil),          // 10: Superplane.ServiceAccounts.DeleteServiceAccountResponse
	(*RegenerateServiceAccountTokenRequest)(nil),  // 11: Superplane.ServiceAccounts.RegenerateServiceAccountTokenRequest
	(*RegenerateServiceAccountTokenResponse)(nil), // 12: Superplane.ServiceAccounts.RegenerateServiceAccountTokenResponse
	(*timestamp.Timestamp)(nil),                   // 13: google.protobuf.Timestamp
}
var file_service_accounts_proto_depIdxs = []int32{
	13, // 0: Superplane.ServiceAccounts.ServiceAccount.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: Superplane.ServiceAccounts.ServiceAccount.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: Superplane.ServiceAccounts.CreateServiceAccountResponse.service_account:type_name -> Superplane.ServiceAccounts.ServiceAccount
	0,  // 3: Superplane.ServiceAccounts.ListServiceAccountsResponse.service_accounts:type_name -> Superplane.ServiceAccounts.ServiceAccount
	0,  // 4: Superplane.ServiceAccounts.DescribeServiceAccountResponse.service_account:type_name -> Superplane.ServiceAccounts.ServiceAccount
	0,  // 5: Superplane.ServiceAccounts.UpdateServiceAccountResponse.service_account:type_name -> Superplane.ServiceAccounts.ServiceAccount
	1,  // 6: Superplane.ServiceAccounts.ServiceAccounts.CreateServiceAccount:input_type -> Superplane.ServiceAccounts.CreateServiceAccountRequest
	3,  // 7: Superplane.ServiceAccounts.ServiceAccounts.ListServiceAccounts:input_type -> Superplane.ServiceAccounts.ListServiceAccountsRequest
	5,  // 8: Superplane.ServiceAccounts.ServiceAccounts.DescribeServiceAccount:input_type -> Superplane.ServiceAccounts.DescribeServiceAccountRequest
	7,  // 9: Superplane.ServiceAccounts.ServiceAccounts.UpdateServiceAccount:input_type -> Superplane.ServiceAccounts.UpdateServiceAccountRequest
	9,  // 10: Superplane.ServiceAccounts.ServiceAccounts.DeleteServiceAccount:input_type -> Superplane.ServiceAccounts.DeleteServiceAccountRequest
	11, // 11: Superplane.ServiceAccounts.ServiceAccounts.RegenerateServiceAccountToken:input_type -> Superplane.ServiceAccounts.RegenerateServiceAccountTokenRequest
	2,  // 12: Superplane.ServiceAccounts.ServiceAccounts.CreateServiceAccount:output_type -> Superplane.ServiceAccounts.CreateServiceAccountResponse
	4,  // 13: Superplane.ServiceAccounts.ServiceAccounts.ListServiceAccounts:output_type -> Superplane.ServiceAccounts.ListServiceAccountsResponse
	6,  // 14: Superplane.ServiceAccounts.ServiceAccounts.DescribeServiceAccount:output_type -> Superplane.ServiceAccounts.DescribeServiceAccountResponse
	8,  // 15: Superplane.ServiceAccounts.ServiceAccounts.UpdateServiceAccount:output_type -> Superplane.ServiceAccounts.UpdateServiceAccountResponse
	10, // 16: Superplane.ServiceAccounts.ServiceAccounts.DeleteServiceAccount:output_type -> Superplane.ServiceAccounts.DeleteServiceAccountResponse
	12, // 17: Superplane.ServiceAccounts.ServiceAccounts.RegenerateServiceAccountToken:output_type -> Superplane.ServiceAccounts.RegenerateServiceAccountTokenResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_service_accounts_proto_init() }
func file_service_accounts_proto_init() {
	if File_service_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_accounts_proto_rawDesc), len(file_service_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_accounts_proto_goTypes,
		DependencyIndexes: file_service_accounts_proto_depIdxs,
		MessageInfos:      file_service_accounts_proto_msgTypes,
	}.Build()
	File_service_accounts_proto = out.File
	file_service_accounts_proto_goTypes = nil
	file_service_accounts_proto_depIdxs = nil
}
