// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `http://${string}` | `https://${string}` | (string & {});
};

/**
 * Enums
 */
export type AuthorizationDomainType = "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";

/**
 * Common data structures
 */
export type AuthorizationPermission = {
  resource?: string;
  action?: string;
  domainType?: AuthorizationDomainType;
};

export type BlueprintsBlueprint = {
  id?: string;
  organizationId?: string;
  name?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  nodes?: Array<ComponentsNode>;
  edges?: Array<ComponentsEdge>;
  configuration?: Array<ConfigurationField>;
  outputChannels?: Array<SuperplaneBlueprintsOutputChannel>;
  icon?: string;
  color?: string;
  createdBy?: SuperplaneBlueprintsUserRef;
};

export type BlueprintsCreateBlueprintRequest = {
  blueprint?: BlueprintsBlueprint;
};

export type BlueprintsCreateBlueprintResponse = {
  blueprint?: BlueprintsBlueprint;
};

export type BlueprintsDeleteBlueprintResponse = {
  [key: string]: unknown;
};

export type BlueprintsDescribeBlueprintResponse = {
  blueprint?: BlueprintsBlueprint;
};

export type BlueprintsListBlueprintsResponse = {
  blueprints?: Array<BlueprintsBlueprint>;
};

export type BlueprintsUpdateBlueprintBody = {
  blueprint?: BlueprintsBlueprint;
};

export type BlueprintsUpdateBlueprintResponse = {
  blueprint?: BlueprintsBlueprint;
};

export type CanvasNodeExecutionResult = "RESULT_UNKNOWN" | "RESULT_PASSED" | "RESULT_FAILED" | "RESULT_CANCELLED";

export type CanvasNodeExecutionResultReason =
  | "RESULT_REASON_OK"
  | "RESULT_REASON_ERROR"
  | "RESULT_REASON_ERROR_RESOLVED";

export type CanvasNodeExecutionState = "STATE_UNKNOWN" | "STATE_PENDING" | "STATE_STARTED" | "STATE_FINISHED";

export type CanvasesCancelExecutionBody = {
  [key: string]: unknown;
};

export type CanvasesCancelExecutionResponse = {
  [key: string]: unknown;
};

export type CanvasesCanvas = {
  metadata?: CanvasesCanvasMetadata;
  spec?: CanvasesCanvasSpec;
  status?: CanvasesCanvasStatus;
};

export type CanvasesCanvasEvent = {
  id?: string;
  canvasId?: string;
  nodeId?: string;
  channel?: string;
  customName?: string;
  data?: {
    [key: string]: unknown;
  };
  createdAt?: string;
};

export type CanvasesCanvasEventWithExecutions = {
  id?: string;
  canvasId?: string;
  nodeId?: string;
  channel?: string;
  data?: {
    [key: string]: unknown;
  };
  createdAt?: string;
  executions?: Array<CanvasesCanvasNodeExecution>;
  customName?: string;
};

export type CanvasesCanvasMetadata = {
  id?: string;
  organizationId?: string;
  name?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: SuperplaneCanvasesUserRef;
  isTemplate?: boolean;
};

export type CanvasesCanvasNodeExecution = {
  id?: string;
  canvasId?: string;
  nodeId?: string;
  parentExecutionId?: string;
  previousExecutionId?: string;
  state?: CanvasNodeExecutionState;
  result?: CanvasNodeExecutionResult;
  resultReason?: CanvasNodeExecutionResultReason;
  resultMessage?: string;
  input?: {
    [key: string]: unknown;
  };
  outputs?: {
    [key: string]: unknown;
  };
  createdAt?: string;
  updatedAt?: string;
  metadata?: {
    [key: string]: unknown;
  };
  configuration?: {
    [key: string]: unknown;
  };
  childExecutions?: Array<CanvasesCanvasNodeExecution>;
  rootEvent?: CanvasesCanvasEvent;
  cancelledBy?: SuperplaneCanvasesUserRef;
};

export type CanvasesCanvasNodeQueueItem = {
  id?: string;
  canvasId?: string;
  nodeId?: string;
  input?: {
    [key: string]: unknown;
  };
  rootEvent?: CanvasesCanvasEvent;
  createdAt?: string;
};

export type CanvasesCanvasSpec = {
  nodes?: Array<ComponentsNode>;
  edges?: Array<ComponentsEdge>;
};

export type CanvasesCanvasStatus = {
  lastExecutions?: Array<CanvasesCanvasNodeExecution>;
  nextQueueItems?: Array<CanvasesCanvasNodeQueueItem>;
  lastEvents?: Array<CanvasesCanvasEvent>;
};

export type CanvasesCreateCanvasRequest = {
  canvas?: CanvasesCanvas;
};

export type CanvasesCreateCanvasResponse = {
  canvas?: CanvasesCanvas;
};

export type CanvasesDeleteCanvasResponse = {
  [key: string]: unknown;
};

export type CanvasesDeleteNodeQueueItemResponse = {
  [key: string]: unknown;
};

export type CanvasesDescribeCanvasResponse = {
  canvas?: CanvasesCanvas;
};

export type CanvasesEmitNodeEventBody = {
  channel?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type CanvasesEmitNodeEventResponse = {
  eventId?: string;
};

export type CanvasesInvokeNodeExecutionActionBody = {
  parameters?: {
    [key: string]: unknown;
  };
};

export type CanvasesInvokeNodeExecutionActionResponse = {
  [key: string]: unknown;
};

export type CanvasesInvokeNodeTriggerActionBody = {
  parameters?: {
    [key: string]: unknown;
  };
};

export type CanvasesInvokeNodeTriggerActionResponse = {
  result?: {
    [key: string]: unknown;
  };
};

export type CanvasesListCanvasEventsResponse = {
  events?: Array<CanvasesCanvasEventWithExecutions>;
  totalCount?: number;
  hasNextPage?: boolean;
  lastTimestamp?: string;
};

export type CanvasesListCanvasesResponse = {
  canvases?: Array<CanvasesCanvas>;
};

export type CanvasesListChildExecutionsBody = {
  [key: string]: unknown;
};

export type CanvasesListChildExecutionsResponse = {
  executions?: Array<CanvasesCanvasNodeExecution>;
};

export type CanvasesListEventExecutionsResponse = {
  executions?: Array<CanvasesCanvasNodeExecution>;
};

export type CanvasesListNodeEventsResponse = {
  events?: Array<CanvasesCanvasEvent>;
  totalCount?: number;
  hasNextPage?: boolean;
  lastTimestamp?: string;
};

export type CanvasesListNodeExecutionsResponse = {
  executions?: Array<CanvasesCanvasNodeExecution>;
  totalCount?: number;
  hasNextPage?: boolean;
  lastTimestamp?: string;
};

export type CanvasesListNodeQueueItemsResponse = {
  items?: Array<CanvasesCanvasNodeQueueItem>;
  totalCount?: number;
  hasNextPage?: boolean;
  lastTimestamp?: string;
};

export type CanvasesResolveExecutionErrorsBody = {
  executionIds?: Array<string>;
};

export type CanvasesResolveExecutionErrorsResponse = {
  [key: string]: unknown;
};

export type CanvasesUpdateCanvasBody = {
  canvas?: CanvasesCanvas;
};

export type CanvasesUpdateCanvasResponse = {
  canvas?: CanvasesCanvas;
};

export type CanvasesUpdateNodePauseBody = {
  paused?: boolean;
};

export type CanvasesUpdateNodePauseResponse = {
  node?: ComponentsNode;
};

export type ComponentsComponent = {
  name?: string;
  label?: string;
  description?: string;
  configuration?: Array<ConfigurationField>;
  outputChannels?: Array<SuperplaneComponentsOutputChannel>;
  icon?: string;
  color?: string;
  exampleOutput?: {
    [key: string]: unknown;
  };
};

export type ComponentsComponentAction = {
  name?: string;
  description?: string;
  parameters?: Array<ConfigurationField>;
};

export type ComponentsDescribeComponentResponse = {
  component?: ComponentsComponent;
};

export type ComponentsEdge = {
  sourceId?: string;
  targetId?: string;
  channel?: string;
};

export type ComponentsIntegrationRef = {
  id?: string;
  name?: string;
};

export type ComponentsListComponentActionsResponse = {
  actions?: Array<ComponentsComponentAction>;
};

export type ComponentsListComponentsResponse = {
  components?: Array<ComponentsComponent>;
};

export type ComponentsNode = {
  id?: string;
  name?: string;
  type?: ComponentsNodeType;
  configuration?: {
    [key: string]: unknown;
  };
  metadata?: {
    [key: string]: unknown;
  };
  position?: ComponentsPosition;
  component?: NodeComponentRef;
  blueprint?: NodeBlueprintRef;
  trigger?: NodeTriggerRef;
  widget?: NodeWidgetRef;
  isCollapsed?: boolean;
  integration?: ComponentsIntegrationRef;
  errorMessage?: string;
  warningMessage?: string;
  paused?: boolean;
};

export type ComponentsNodeType = "TYPE_COMPONENT" | "TYPE_BLUEPRINT" | "TYPE_TRIGGER" | "TYPE_WIDGET";

export type ComponentsPosition = {
  x?: number;
  y?: number;
};

export type ConfigurationAnyPredicateListTypeOptions = {
  operators?: Array<ConfigurationSelectOption>;
};

export type ConfigurationDateTimeTypeOptions = {
  format?: string;
};

export type ConfigurationDateTypeOptions = {
  format?: string;
};

export type ConfigurationExpressionTypeOptions = {
  minLength?: number;
  maxLength?: number;
};

export type ConfigurationField = {
  name?: string;
  type?: string;
  description?: string;
  required?: boolean;
  defaultValue?: string;
  label?: string;
  visibilityConditions?: Array<ConfigurationVisibilityCondition>;
  typeOptions?: ConfigurationTypeOptions;
  requiredConditions?: Array<ConfigurationRequiredCondition>;
  validationRules?: Array<ConfigurationValidationRule>;
  placeholder?: string;
  sensitive?: boolean;
  togglable?: boolean;
  disallowExpression?: boolean;
};

export type ConfigurationListItemDefinition = {
  type?: string;
  schema?: Array<ConfigurationField>;
};

export type ConfigurationListTypeOptions = {
  itemDefinition?: ConfigurationListItemDefinition;
  itemLabel?: string;
};

export type ConfigurationMultiSelectTypeOptions = {
  options?: Array<ConfigurationSelectOption>;
};

export type ConfigurationNumberTypeOptions = {
  min?: number;
  max?: number;
};

export type ConfigurationObjectTypeOptions = {
  schema?: Array<ConfigurationField>;
};

export type ConfigurationParameterRef = {
  name?: string;
  value?: string;
  valueFrom?: ConfigurationParameterValueFrom;
};

export type ConfigurationParameterValueFrom = {
  field?: string;
};

export type ConfigurationRequiredCondition = {
  field?: string;
  values?: Array<string>;
};

export type ConfigurationResourceTypeOptions = {
  type?: string;
  useNameAsValue?: boolean;
  multi?: boolean;
  parameters?: Array<ConfigurationParameterRef>;
};

export type ConfigurationSelectOption = {
  label?: string;
  value?: string;
};

export type ConfigurationSelectTypeOptions = {
  options?: Array<ConfigurationSelectOption>;
};

export type ConfigurationStringTypeOptions = {
  minLength?: number;
  maxLength?: number;
};

export type ConfigurationTextTypeOptions = {
  minLength?: number;
  maxLength?: number;
};

export type ConfigurationTimeTypeOptions = {
  format?: string;
};

export type ConfigurationTypeOptions = {
  number?: ConfigurationNumberTypeOptions;
  select?: ConfigurationSelectTypeOptions;
  multiSelect?: ConfigurationMultiSelectTypeOptions;
  list?: ConfigurationListTypeOptions;
  object?: ConfigurationObjectTypeOptions;
  resource?: ConfigurationResourceTypeOptions;
  time?: ConfigurationTimeTypeOptions;
  date?: ConfigurationDateTypeOptions;
  datetime?: ConfigurationDateTimeTypeOptions;
  anyPredicateList?: ConfigurationAnyPredicateListTypeOptions;
  string?: ConfigurationStringTypeOptions;
  expression?: ConfigurationExpressionTypeOptions;
  text?: ConfigurationTextTypeOptions;
};

export type ConfigurationValidationRule = {
  type?: string;
  compareWith?: string;
  message?: string;
};

export type ConfigurationVisibilityCondition = {
  field?: string;
  values?: Array<string>;
};

export type GroupsAddUserToGroupBody = {
  domainType?: AuthorizationDomainType;
  domainId?: string;
  userId?: string;
  userEmail?: string;
};

export type GroupsAddUserToGroupResponse = {
  [key: string]: unknown;
};

export type GroupsCreateGroupRequest = {
  domainType?: AuthorizationDomainType;
  domainId?: string;
  group?: GroupsGroup;
};

export type GroupsCreateGroupResponse = {
  group?: GroupsGroup;
};

export type GroupsDeleteGroupResponse = {
  [key: string]: unknown;
};

export type GroupsDescribeGroupResponse = {
  group?: GroupsGroup;
};

export type GroupsGroup = {
  metadata?: GroupsGroupMetadata;
  spec?: GroupsGroupSpec;
  status?: GroupsGroupStatus;
};

export type GroupsGroupMetadata = {
  name?: string;
  domainType?: AuthorizationDomainType;
  domainId?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type GroupsGroupSpec = {
  role?: string;
  displayName?: string;
  description?: string;
};

export type GroupsGroupStatus = {
  membersCount?: number;
};

export type GroupsListGroupUsersResponse = {
  users?: Array<SuperplaneUsersUser>;
  group?: GroupsGroup;
};

export type GroupsListGroupsResponse = {
  groups?: Array<GroupsGroup>;
};

export type GroupsRemoveUserFromGroupBody = {
  domainType?: AuthorizationDomainType;
  domainId?: string;
  userId?: string;
  userEmail?: string;
};

export type GroupsRemoveUserFromGroupResponse = {
  [key: string]: unknown;
};

export type GroupsUpdateGroupBody = {
  domainType?: AuthorizationDomainType;
  domainId?: string;
  group?: GroupsGroup;
};

export type GroupsUpdateGroupResponse = {
  group?: GroupsGroup;
};

export type IntegrationNodeRef = {
  canvasId?: string;
  canvasName?: string;
  nodeId?: string;
  nodeName?: string;
};

export type IntegrationsIntegrationDefinition = {
  name?: string;
  label?: string;
  icon?: string;
  description?: string;
  configuration?: Array<ConfigurationField>;
  components?: Array<ComponentsComponent>;
  triggers?: Array<TriggersTrigger>;
  instructions?: string;
};

export type MeRegenerateTokenResponse = {
  token?: string;
};

export type NodeBlueprintRef = {
  id?: string;
};

export type NodeComponentRef = {
  name?: string;
};

export type NodeTriggerRef = {
  name?: string;
};

export type NodeWidgetRef = {
  name?: string;
};

export type OrganizationsBrowserAction = {
  url?: string;
  method?: string;
  formFields?: {
    [key: string]: string;
  };
  description?: string;
};

export type OrganizationsCreateIntegrationBody = {
  name?: string;
  integrationName?: string;
  configuration?: {
    [key: string]: unknown;
  };
};

export type OrganizationsCreateIntegrationResponse = {
  integration?: OrganizationsIntegration;
};

export type OrganizationsCreateInvitationBody = {
  email?: string;
};

export type OrganizationsCreateInvitationResponse = {
  invitation?: OrganizationsInvitation;
};

export type OrganizationsDeleteIntegrationResponse = {
  [key: string]: unknown;
};

export type OrganizationsDeleteOrganizationResponse = {
  [key: string]: unknown;
};

export type OrganizationsDescribeIntegrationResponse = {
  integration?: OrganizationsIntegration;
};

export type OrganizationsDescribeOrganizationResponse = {
  organization?: OrganizationsOrganization;
};

export type OrganizationsGetInviteLinkResponse = {
  inviteLink?: OrganizationsInviteLink;
};

export type OrganizationsIntegration = {
  metadata?: OrganizationsIntegrationMetadata;
  spec?: OrganizationsIntegrationSpec;
  status?: OrganizationsIntegrationStatus;
};

export type OrganizationsIntegrationMetadata = {
  id?: string;
  name?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type OrganizationsIntegrationResourceRef = {
  type?: string;
  name?: string;
  id?: string;
};

export type OrganizationsIntegrationSpec = {
  integrationName?: string;
  configuration?: {
    [key: string]: unknown;
  };
};

export type OrganizationsIntegrationStatus = {
  state?: string;
  stateDescription?: string;
  metadata?: {
    [key: string]: unknown;
  };
  browserAction?: OrganizationsBrowserAction;
  usedIn?: Array<IntegrationNodeRef>;
};

export type OrganizationsInvitation = {
  id?: string;
  organizationId?: string;
  email?: string;
  state?: string;
  createdAt?: string;
};

export type OrganizationsInviteLink = {
  id?: string;
  organizationId?: string;
  token?: string;
  enabled?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type OrganizationsListIntegrationResourcesResponse = {
  resources?: Array<OrganizationsIntegrationResourceRef>;
};

export type OrganizationsListInvitationsResponse = {
  invitations?: Array<OrganizationsInvitation>;
};

export type OrganizationsOrganization = {
  metadata?: OrganizationsOrganizationMetadata;
};

export type OrganizationsOrganizationMetadata = {
  id?: string;
  name?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type OrganizationsRemoveInvitationResponse = {
  [key: string]: unknown;
};

export type OrganizationsRemoveUserResponse = {
  [key: string]: unknown;
};

export type OrganizationsResetInviteLinkResponse = {
  inviteLink?: OrganizationsInviteLink;
};

export type OrganizationsUpdateIntegrationBody = {
  configuration?: {
    [key: string]: unknown;
  };
  name?: string;
};

export type OrganizationsUpdateIntegrationResponse = {
  integration?: OrganizationsIntegration;
};

export type OrganizationsUpdateInviteLinkBody = {
  enabled?: boolean;
};

export type OrganizationsUpdateInviteLinkResponse = {
  inviteLink?: OrganizationsInviteLink;
};

export type OrganizationsUpdateOrganizationBody = {
  organization?: OrganizationsOrganization;
};

export type OrganizationsUpdateOrganizationResponse = {
  organization?: OrganizationsOrganization;
};

export type RolesAssignRoleBody = {
  domainType?: AuthorizationDomainType;
  domainId?: string;
  userId?: string;
  userEmail?: string;
};

export type RolesAssignRoleResponse = {
  [key: string]: unknown;
};

export type RolesCreateRoleRequest = {
  domainType?: AuthorizationDomainType;
  domainId?: string;
  role?: RolesRole;
};

export type RolesCreateRoleResponse = {
  role?: RolesRole;
};

export type RolesDeleteRoleResponse = {
  [key: string]: unknown;
};

export type RolesDescribeRoleResponse = {
  role?: RolesRole;
};

export type RolesListRolesResponse = {
  roles?: Array<RolesRole>;
};

export type RolesRole = {
  metadata?: RolesRoleMetadata;
  spec?: RolesRoleSpec;
};

export type RolesRoleMetadata = {
  name?: string;
  domainType?: AuthorizationDomainType;
  domainId?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type RolesRoleSpec = {
  displayName?: string;
  description?: string;
  permissions?: Array<AuthorizationPermission>;
  inheritedRole?: RolesRole;
};

export type RolesUpdateRoleBody = {
  domainType?: AuthorizationDomainType;
  domainId?: string;
  role?: RolesRole;
};

export type RolesUpdateRoleResponse = {
  role?: RolesRole;
};

/**
 * Local secrets are stored and managed by SuperPlane itself.
 */
export type SecretLocal = {
  data?: {
    [key: string]: string;
  };
};

export type SecretProvider = "PROVIDER_UNKNOWN" | "PROVIDER_LOCAL";

export type SecretsCreateSecretRequest = {
  secret?: SecretsSecret;
  domainType?: AuthorizationDomainType;
  domainId?: string;
};

export type SecretsCreateSecretResponse = {
  secret?: SecretsSecret;
};

export type SecretsDeleteSecretKeyResponse = {
  secret?: SecretsSecret;
};

export type SecretsDeleteSecretResponse = {
  [key: string]: unknown;
};

export type SecretsDescribeSecretResponse = {
  secret?: SecretsSecret;
};

export type SecretsListSecretsResponse = {
  secrets?: Array<SecretsSecret>;
};

export type SecretsSecret = {
  metadata?: SecretsSecretMetadata;
  spec?: SecretsSecretSpec;
};

export type SecretsSecretMetadata = {
  id?: string;
  name?: string;
  domainType?: AuthorizationDomainType;
  domainId?: string;
  createdAt?: string;
};

export type SecretsSecretSpec = {
  provider?: SecretProvider;
  local?: SecretLocal;
};

export type SecretsSetSecretKeyBody = {
  value?: string;
  domainType?: AuthorizationDomainType;
  domainId?: string;
};

export type SecretsSetSecretKeyResponse = {
  secret?: SecretsSecret;
};

export type SecretsUpdateSecretBody = {
  secret?: SecretsSecret;
  domainType?: AuthorizationDomainType;
  domainId?: string;
};

export type SecretsUpdateSecretNameBody = {
  name?: string;
  domainType?: AuthorizationDomainType;
  domainId?: string;
};

export type SecretsUpdateSecretNameResponse = {
  secret?: SecretsSecret;
};

export type SecretsUpdateSecretResponse = {
  secret?: SecretsSecret;
};

export type ServiceAccountsCreateServiceAccountRequest = {
  name?: string;
  description?: string;
  role?: string;
};

export type ServiceAccountsCreateServiceAccountResponse = {
  serviceAccount?: ServiceAccountsServiceAccount;
  token?: string;
};

export type ServiceAccountsDeleteServiceAccountResponse = {
  [key: string]: unknown;
};

export type ServiceAccountsDescribeServiceAccountResponse = {
  serviceAccount?: ServiceAccountsServiceAccount;
};

export type ServiceAccountsListServiceAccountsResponse = {
  serviceAccounts?: Array<ServiceAccountsServiceAccount>;
};

export type ServiceAccountsRegenerateServiceAccountTokenBody = {
  [key: string]: unknown;
};

export type ServiceAccountsRegenerateServiceAccountTokenResponse = {
  token?: string;
};

export type ServiceAccountsServiceAccount = {
  id?: string;
  name?: string;
  description?: string;
  organizationId?: string;
  createdBy?: string;
  hasToken?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type ServiceAccountsUpdateServiceAccountBody = {
  name?: string;
  description?: string;
};

export type ServiceAccountsUpdateServiceAccountResponse = {
  serviceAccount?: ServiceAccountsServiceAccount;
};

export type SuperplaneBlueprintsOutputChannel = {
  name?: string;
  nodeId?: string;
  nodeOutputChannel?: string;
};

export type SuperplaneBlueprintsUserRef = {
  id?: string;
  name?: string;
};

export type SuperplaneCanvasesUserRef = {
  id?: string;
  name?: string;
};

export type SuperplaneComponentsOutputChannel = {
  name?: string;
  label?: string;
  description?: string;
};

export type SuperplaneIntegrationsListIntegrationsResponse = {
  integrations?: Array<IntegrationsIntegrationDefinition>;
};

export type SuperplaneMeUser = {
  id?: string;
  email?: string;
  organizationId?: string;
  createdAt?: string;
  hasToken?: boolean;
};

export type SuperplaneOrganizationsListIntegrationsResponse = {
  integrations?: Array<OrganizationsIntegration>;
};

export type SuperplaneUsersUser = {
  metadata?: UsersUserMetadata;
  spec?: UsersUserSpec;
  status?: UsersUserStatus;
};

export type TriggersDescribeTriggerResponse = {
  trigger?: TriggersTrigger;
};

export type TriggersListTriggersResponse = {
  triggers?: Array<TriggersTrigger>;
};

export type TriggersTrigger = {
  name?: string;
  label?: string;
  description?: string;
  icon?: string;
  color?: string;
  configuration?: Array<ConfigurationField>;
  exampleData?: {
    [key: string]: unknown;
  };
};

export type UsersAccountProvider = {
  providerType?: string;
  providerId?: string;
  email?: string;
  displayName?: string;
  avatarUrl?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type UsersListUserPermissionsResponse = {
  userId?: string;
  domainType?: AuthorizationDomainType;
  domainId?: string;
  permissions?: Array<AuthorizationPermission>;
};

export type UsersListUserRolesResponse = {
  userId?: string;
  domainType?: AuthorizationDomainType;
  domainId?: string;
  roles?: Array<RolesRole>;
};

export type UsersListUsersResponse = {
  users?: Array<SuperplaneUsersUser>;
};

export type UsersUserMetadata = {
  id?: string;
  email?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type UsersUserRoleAssignment = {
  roleName?: string;
  roleDisplayName?: string;
  roleDescription?: string;
  domainType?: AuthorizationDomainType;
  domainId?: string;
  assignedAt?: string;
};

export type UsersUserSpec = {
  displayName?: string;
  accountProviders?: Array<UsersAccountProvider>;
};

export type UsersUserStatus = {
  roleAssignments?: Array<UsersUserRoleAssignment>;
};

export type WidgetsDescribeWidgetResponse = {
  widget?: WidgetsWidget;
};

export type WidgetsListWidgetsResponse = {
  widgets?: Array<WidgetsWidget>;
};

export type WidgetsWidget = {
  name?: string;
  label?: string;
  description?: string;
  icon?: string;
  color?: string;
  configuration?: Array<ConfigurationField>;
};

export type GooglerpcStatus = {
  code?: number;
  message?: string;
  details?: Array<ProtobufAny>;
};

export type ProtobufAny = {
  "@type"?: string;
  [key: string]: unknown | string | undefined;
};

/**
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 *
 * The JSON representation for `NullValue` is JSON `null`.
 *
 * - NULL_VALUE: Null value.
 */
export type ProtobufNullValue = "NULL_VALUE";

export type BlueprintsListBlueprintsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/blueprints";
};

export type BlueprintsListBlueprintsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type BlueprintsListBlueprintsError = BlueprintsListBlueprintsErrors[keyof BlueprintsListBlueprintsErrors];

export type BlueprintsListBlueprintsResponses = {
  /**
   * A successful response.
   */
  200: BlueprintsListBlueprintsResponse;
};

export type BlueprintsListBlueprintsResponse2 =
  BlueprintsListBlueprintsResponses[keyof BlueprintsListBlueprintsResponses];

export type BlueprintsCreateBlueprintData = {
  body: BlueprintsCreateBlueprintRequest;
  path?: never;
  query?: never;
  url: "/api/v1/blueprints";
};

export type BlueprintsCreateBlueprintErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type BlueprintsCreateBlueprintError = BlueprintsCreateBlueprintErrors[keyof BlueprintsCreateBlueprintErrors];

export type BlueprintsCreateBlueprintResponses = {
  /**
   * A successful response.
   */
  200: BlueprintsCreateBlueprintResponse;
};

export type BlueprintsCreateBlueprintResponse2 =
  BlueprintsCreateBlueprintResponses[keyof BlueprintsCreateBlueprintResponses];

export type BlueprintsDeleteBlueprintData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/blueprints/{id}";
};

export type BlueprintsDeleteBlueprintErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type BlueprintsDeleteBlueprintError = BlueprintsDeleteBlueprintErrors[keyof BlueprintsDeleteBlueprintErrors];

export type BlueprintsDeleteBlueprintResponses = {
  /**
   * A successful response.
   */
  200: BlueprintsDeleteBlueprintResponse;
};

export type BlueprintsDeleteBlueprintResponse2 =
  BlueprintsDeleteBlueprintResponses[keyof BlueprintsDeleteBlueprintResponses];

export type BlueprintsDescribeBlueprintData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/blueprints/{id}";
};

export type BlueprintsDescribeBlueprintErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type BlueprintsDescribeBlueprintError =
  BlueprintsDescribeBlueprintErrors[keyof BlueprintsDescribeBlueprintErrors];

export type BlueprintsDescribeBlueprintResponses = {
  /**
   * A successful response.
   */
  200: BlueprintsDescribeBlueprintResponse;
};

export type BlueprintsDescribeBlueprintResponse2 =
  BlueprintsDescribeBlueprintResponses[keyof BlueprintsDescribeBlueprintResponses];

export type BlueprintsUpdateBlueprintData = {
  body: BlueprintsUpdateBlueprintBody;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/blueprints/{id}";
};

export type BlueprintsUpdateBlueprintErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type BlueprintsUpdateBlueprintError = BlueprintsUpdateBlueprintErrors[keyof BlueprintsUpdateBlueprintErrors];

export type BlueprintsUpdateBlueprintResponses = {
  /**
   * A successful response.
   */
  200: BlueprintsUpdateBlueprintResponse;
};

export type BlueprintsUpdateBlueprintResponse2 =
  BlueprintsUpdateBlueprintResponses[keyof BlueprintsUpdateBlueprintResponses];

export type CanvasesListCanvasesData = {
  body?: never;
  path?: never;
  query?: {
    includeTemplates?: boolean;
  };
  url: "/api/v1/canvases";
};

export type CanvasesListCanvasesErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesListCanvasesError = CanvasesListCanvasesErrors[keyof CanvasesListCanvasesErrors];

export type CanvasesListCanvasesResponses = {
  /**
   * A successful response.
   */
  200: CanvasesListCanvasesResponse;
};

export type CanvasesListCanvasesResponse2 = CanvasesListCanvasesResponses[keyof CanvasesListCanvasesResponses];

export type CanvasesCreateCanvasData = {
  body: CanvasesCreateCanvasRequest;
  path?: never;
  query?: never;
  url: "/api/v1/canvases";
};

export type CanvasesCreateCanvasErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesCreateCanvasError = CanvasesCreateCanvasErrors[keyof CanvasesCreateCanvasErrors];

export type CanvasesCreateCanvasResponses = {
  /**
   * A successful response.
   */
  200: CanvasesCreateCanvasResponse;
};

export type CanvasesCreateCanvasResponse2 = CanvasesCreateCanvasResponses[keyof CanvasesCreateCanvasResponses];

export type CanvasesListCanvasEventsData = {
  body?: never;
  path: {
    canvasId: string;
  };
  query?: {
    limit?: number;
    before?: string;
  };
  url: "/api/v1/canvases/{canvasId}/events";
};

export type CanvasesListCanvasEventsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesListCanvasEventsError = CanvasesListCanvasEventsErrors[keyof CanvasesListCanvasEventsErrors];

export type CanvasesListCanvasEventsResponses = {
  /**
   * A successful response.
   */
  200: CanvasesListCanvasEventsResponse;
};

export type CanvasesListCanvasEventsResponse2 =
  CanvasesListCanvasEventsResponses[keyof CanvasesListCanvasEventsResponses];

export type CanvasesListEventExecutionsData = {
  body?: never;
  path: {
    canvasId: string;
    eventId: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/events/{eventId}/executions";
};

export type CanvasesListEventExecutionsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesListEventExecutionsError =
  CanvasesListEventExecutionsErrors[keyof CanvasesListEventExecutionsErrors];

export type CanvasesListEventExecutionsResponses = {
  /**
   * A successful response.
   */
  200: CanvasesListEventExecutionsResponse;
};

export type CanvasesListEventExecutionsResponse2 =
  CanvasesListEventExecutionsResponses[keyof CanvasesListEventExecutionsResponses];

export type CanvasesResolveExecutionErrorsData = {
  body: CanvasesResolveExecutionErrorsBody;
  path: {
    canvasId: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/executions/resolve";
};

export type CanvasesResolveExecutionErrorsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesResolveExecutionErrorsError =
  CanvasesResolveExecutionErrorsErrors[keyof CanvasesResolveExecutionErrorsErrors];

export type CanvasesResolveExecutionErrorsResponses = {
  /**
   * A successful response.
   */
  200: CanvasesResolveExecutionErrorsResponse;
};

export type CanvasesResolveExecutionErrorsResponse2 =
  CanvasesResolveExecutionErrorsResponses[keyof CanvasesResolveExecutionErrorsResponses];

export type CanvasesInvokeNodeExecutionActionData = {
  body: CanvasesInvokeNodeExecutionActionBody;
  path: {
    canvasId: string;
    executionId: string;
    actionName: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/executions/{executionId}/actions/{actionName}";
};

export type CanvasesInvokeNodeExecutionActionErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesInvokeNodeExecutionActionError =
  CanvasesInvokeNodeExecutionActionErrors[keyof CanvasesInvokeNodeExecutionActionErrors];

export type CanvasesInvokeNodeExecutionActionResponses = {
  /**
   * A successful response.
   */
  200: CanvasesInvokeNodeExecutionActionResponse;
};

export type CanvasesInvokeNodeExecutionActionResponse2 =
  CanvasesInvokeNodeExecutionActionResponses[keyof CanvasesInvokeNodeExecutionActionResponses];

export type CanvasesCancelExecutionData = {
  body: CanvasesCancelExecutionBody;
  path: {
    canvasId: string;
    executionId: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/executions/{executionId}/cancel";
};

export type CanvasesCancelExecutionErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesCancelExecutionError = CanvasesCancelExecutionErrors[keyof CanvasesCancelExecutionErrors];

export type CanvasesCancelExecutionResponses = {
  /**
   * A successful response.
   */
  200: CanvasesCancelExecutionResponse;
};

export type CanvasesCancelExecutionResponse2 = CanvasesCancelExecutionResponses[keyof CanvasesCancelExecutionResponses];

export type CanvasesListChildExecutionsData = {
  body: CanvasesListChildExecutionsBody;
  path: {
    canvasId: string;
    executionId: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/executions/{executionId}/children";
};

export type CanvasesListChildExecutionsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesListChildExecutionsError =
  CanvasesListChildExecutionsErrors[keyof CanvasesListChildExecutionsErrors];

export type CanvasesListChildExecutionsResponses = {
  /**
   * A successful response.
   */
  200: CanvasesListChildExecutionsResponse;
};

export type CanvasesListChildExecutionsResponse2 =
  CanvasesListChildExecutionsResponses[keyof CanvasesListChildExecutionsResponses];

export type CanvasesListNodeEventsData = {
  body?: never;
  path: {
    canvasId: string;
    nodeId: string;
  };
  query?: {
    limit?: number;
    before?: string;
  };
  url: "/api/v1/canvases/{canvasId}/nodes/{nodeId}/events";
};

export type CanvasesListNodeEventsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesListNodeEventsError = CanvasesListNodeEventsErrors[keyof CanvasesListNodeEventsErrors];

export type CanvasesListNodeEventsResponses = {
  /**
   * A successful response.
   */
  200: CanvasesListNodeEventsResponse;
};

export type CanvasesListNodeEventsResponse2 = CanvasesListNodeEventsResponses[keyof CanvasesListNodeEventsResponses];

export type CanvasesEmitNodeEventData = {
  body: CanvasesEmitNodeEventBody;
  path: {
    canvasId: string;
    nodeId: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/nodes/{nodeId}/events";
};

export type CanvasesEmitNodeEventErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesEmitNodeEventError = CanvasesEmitNodeEventErrors[keyof CanvasesEmitNodeEventErrors];

export type CanvasesEmitNodeEventResponses = {
  /**
   * A successful response.
   */
  200: CanvasesEmitNodeEventResponse;
};

export type CanvasesEmitNodeEventResponse2 = CanvasesEmitNodeEventResponses[keyof CanvasesEmitNodeEventResponses];

export type CanvasesListNodeExecutionsData = {
  body?: never;
  path: {
    canvasId: string;
    nodeId: string;
  };
  query?: {
    states?: Array<"STATE_UNKNOWN" | "STATE_PENDING" | "STATE_STARTED" | "STATE_FINISHED">;
    results?: Array<"RESULT_UNKNOWN" | "RESULT_PASSED" | "RESULT_FAILED" | "RESULT_CANCELLED">;
    limit?: number;
    before?: string;
  };
  url: "/api/v1/canvases/{canvasId}/nodes/{nodeId}/executions";
};

export type CanvasesListNodeExecutionsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesListNodeExecutionsError = CanvasesListNodeExecutionsErrors[keyof CanvasesListNodeExecutionsErrors];

export type CanvasesListNodeExecutionsResponses = {
  /**
   * A successful response.
   */
  200: CanvasesListNodeExecutionsResponse;
};

export type CanvasesListNodeExecutionsResponse2 =
  CanvasesListNodeExecutionsResponses[keyof CanvasesListNodeExecutionsResponses];

export type CanvasesUpdateNodePauseData = {
  body: CanvasesUpdateNodePauseBody;
  path: {
    canvasId: string;
    nodeId: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/nodes/{nodeId}/pause";
};

export type CanvasesUpdateNodePauseErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesUpdateNodePauseError = CanvasesUpdateNodePauseErrors[keyof CanvasesUpdateNodePauseErrors];

export type CanvasesUpdateNodePauseResponses = {
  /**
   * A successful response.
   */
  200: CanvasesUpdateNodePauseResponse;
};

export type CanvasesUpdateNodePauseResponse2 = CanvasesUpdateNodePauseResponses[keyof CanvasesUpdateNodePauseResponses];

export type CanvasesListNodeQueueItemsData = {
  body?: never;
  path: {
    canvasId: string;
    nodeId: string;
  };
  query?: {
    limit?: number;
    before?: string;
  };
  url: "/api/v1/canvases/{canvasId}/nodes/{nodeId}/queue";
};

export type CanvasesListNodeQueueItemsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesListNodeQueueItemsError = CanvasesListNodeQueueItemsErrors[keyof CanvasesListNodeQueueItemsErrors];

export type CanvasesListNodeQueueItemsResponses = {
  /**
   * A successful response.
   */
  200: CanvasesListNodeQueueItemsResponse;
};

export type CanvasesListNodeQueueItemsResponse2 =
  CanvasesListNodeQueueItemsResponses[keyof CanvasesListNodeQueueItemsResponses];

export type CanvasesDeleteNodeQueueItemData = {
  body?: never;
  path: {
    canvasId: string;
    nodeId: string;
    itemId: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/nodes/{nodeId}/queue/{itemId}";
};

export type CanvasesDeleteNodeQueueItemErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesDeleteNodeQueueItemError =
  CanvasesDeleteNodeQueueItemErrors[keyof CanvasesDeleteNodeQueueItemErrors];

export type CanvasesDeleteNodeQueueItemResponses = {
  /**
   * A successful response.
   */
  200: CanvasesDeleteNodeQueueItemResponse;
};

export type CanvasesDeleteNodeQueueItemResponse2 =
  CanvasesDeleteNodeQueueItemResponses[keyof CanvasesDeleteNodeQueueItemResponses];

export type CanvasesInvokeNodeTriggerActionData = {
  body: CanvasesInvokeNodeTriggerActionBody;
  path: {
    canvasId: string;
    nodeId: string;
    actionName: string;
  };
  query?: never;
  url: "/api/v1/canvases/{canvasId}/triggers/{nodeId}/actions/{actionName}";
};

export type CanvasesInvokeNodeTriggerActionErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesInvokeNodeTriggerActionError =
  CanvasesInvokeNodeTriggerActionErrors[keyof CanvasesInvokeNodeTriggerActionErrors];

export type CanvasesInvokeNodeTriggerActionResponses = {
  /**
   * A successful response.
   */
  200: CanvasesInvokeNodeTriggerActionResponse;
};

export type CanvasesInvokeNodeTriggerActionResponse2 =
  CanvasesInvokeNodeTriggerActionResponses[keyof CanvasesInvokeNodeTriggerActionResponses];

export type CanvasesDeleteCanvasData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/canvases/{id}";
};

export type CanvasesDeleteCanvasErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesDeleteCanvasError = CanvasesDeleteCanvasErrors[keyof CanvasesDeleteCanvasErrors];

export type CanvasesDeleteCanvasResponses = {
  /**
   * A successful response.
   */
  200: CanvasesDeleteCanvasResponse;
};

export type CanvasesDeleteCanvasResponse2 = CanvasesDeleteCanvasResponses[keyof CanvasesDeleteCanvasResponses];

export type CanvasesDescribeCanvasData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/canvases/{id}";
};

export type CanvasesDescribeCanvasErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesDescribeCanvasError = CanvasesDescribeCanvasErrors[keyof CanvasesDescribeCanvasErrors];

export type CanvasesDescribeCanvasResponses = {
  /**
   * A successful response.
   */
  200: CanvasesDescribeCanvasResponse;
};

export type CanvasesDescribeCanvasResponse2 = CanvasesDescribeCanvasResponses[keyof CanvasesDescribeCanvasResponses];

export type CanvasesUpdateCanvasData = {
  body: CanvasesUpdateCanvasBody;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/canvases/{id}";
};

export type CanvasesUpdateCanvasErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type CanvasesUpdateCanvasError = CanvasesUpdateCanvasErrors[keyof CanvasesUpdateCanvasErrors];

export type CanvasesUpdateCanvasResponses = {
  /**
   * A successful response.
   */
  200: CanvasesUpdateCanvasResponse;
};

export type CanvasesUpdateCanvasResponse2 = CanvasesUpdateCanvasResponses[keyof CanvasesUpdateCanvasResponses];

export type ComponentsListComponentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/components";
};

export type ComponentsListComponentsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ComponentsListComponentsError = ComponentsListComponentsErrors[keyof ComponentsListComponentsErrors];

export type ComponentsListComponentsResponses = {
  /**
   * A successful response.
   */
  200: ComponentsListComponentsResponse;
};

export type ComponentsListComponentsResponse2 =
  ComponentsListComponentsResponses[keyof ComponentsListComponentsResponses];

export type ComponentsDescribeComponentData = {
  body?: never;
  path: {
    name: string;
  };
  query?: never;
  url: "/api/v1/components/{name}";
};

export type ComponentsDescribeComponentErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ComponentsDescribeComponentError =
  ComponentsDescribeComponentErrors[keyof ComponentsDescribeComponentErrors];

export type ComponentsDescribeComponentResponses = {
  /**
   * A successful response.
   */
  200: ComponentsDescribeComponentResponse;
};

export type ComponentsDescribeComponentResponse2 =
  ComponentsDescribeComponentResponses[keyof ComponentsDescribeComponentResponses];

export type ComponentsListComponentActionsData = {
  body?: never;
  path: {
    name: string;
  };
  query?: never;
  url: "/api/v1/components/{name}/actions";
};

export type ComponentsListComponentActionsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ComponentsListComponentActionsError =
  ComponentsListComponentActionsErrors[keyof ComponentsListComponentActionsErrors];

export type ComponentsListComponentActionsResponses = {
  /**
   * A successful response.
   */
  200: ComponentsListComponentActionsResponse;
};

export type ComponentsListComponentActionsResponse2 =
  ComponentsListComponentActionsResponses[keyof ComponentsListComponentActionsResponses];

export type GroupsListGroupsData = {
  body?: never;
  path?: never;
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/groups";
};

export type GroupsListGroupsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type GroupsListGroupsError = GroupsListGroupsErrors[keyof GroupsListGroupsErrors];

export type GroupsListGroupsResponses = {
  /**
   * A successful response.
   */
  200: GroupsListGroupsResponse;
};

export type GroupsListGroupsResponse2 = GroupsListGroupsResponses[keyof GroupsListGroupsResponses];

export type GroupsCreateGroupData = {
  body: GroupsCreateGroupRequest;
  path?: never;
  query?: never;
  url: "/api/v1/groups";
};

export type GroupsCreateGroupErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type GroupsCreateGroupError = GroupsCreateGroupErrors[keyof GroupsCreateGroupErrors];

export type GroupsCreateGroupResponses = {
  /**
   * A successful response.
   */
  200: GroupsCreateGroupResponse;
};

export type GroupsCreateGroupResponse2 = GroupsCreateGroupResponses[keyof GroupsCreateGroupResponses];

export type GroupsDeleteGroupData = {
  body?: never;
  path: {
    groupName: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/groups/{groupName}";
};

export type GroupsDeleteGroupErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type GroupsDeleteGroupError = GroupsDeleteGroupErrors[keyof GroupsDeleteGroupErrors];

export type GroupsDeleteGroupResponses = {
  /**
   * A successful response.
   */
  200: GroupsDeleteGroupResponse;
};

export type GroupsDeleteGroupResponse2 = GroupsDeleteGroupResponses[keyof GroupsDeleteGroupResponses];

export type GroupsDescribeGroupData = {
  body?: never;
  path: {
    groupName: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/groups/{groupName}";
};

export type GroupsDescribeGroupErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type GroupsDescribeGroupError = GroupsDescribeGroupErrors[keyof GroupsDescribeGroupErrors];

export type GroupsDescribeGroupResponses = {
  /**
   * A successful response.
   */
  200: GroupsDescribeGroupResponse;
};

export type GroupsDescribeGroupResponse2 = GroupsDescribeGroupResponses[keyof GroupsDescribeGroupResponses];

export type GroupsUpdateGroupData = {
  body: GroupsUpdateGroupBody;
  path: {
    groupName: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupName}";
};

export type GroupsUpdateGroupErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type GroupsUpdateGroupError = GroupsUpdateGroupErrors[keyof GroupsUpdateGroupErrors];

export type GroupsUpdateGroupResponses = {
  /**
   * A successful response.
   */
  200: GroupsUpdateGroupResponse;
};

export type GroupsUpdateGroupResponse2 = GroupsUpdateGroupResponses[keyof GroupsUpdateGroupResponses];

export type GroupsListGroupUsersData = {
  body?: never;
  path: {
    groupName: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/groups/{groupName}/users";
};

export type GroupsListGroupUsersErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type GroupsListGroupUsersError = GroupsListGroupUsersErrors[keyof GroupsListGroupUsersErrors];

export type GroupsListGroupUsersResponses = {
  /**
   * A successful response.
   */
  200: GroupsListGroupUsersResponse;
};

export type GroupsListGroupUsersResponse2 = GroupsListGroupUsersResponses[keyof GroupsListGroupUsersResponses];

export type GroupsAddUserToGroupData = {
  body: GroupsAddUserToGroupBody;
  path: {
    groupName: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupName}/users";
};

export type GroupsAddUserToGroupErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type GroupsAddUserToGroupError = GroupsAddUserToGroupErrors[keyof GroupsAddUserToGroupErrors];

export type GroupsAddUserToGroupResponses = {
  /**
   * A successful response.
   */
  200: GroupsAddUserToGroupResponse;
};

export type GroupsAddUserToGroupResponse2 = GroupsAddUserToGroupResponses[keyof GroupsAddUserToGroupResponses];

export type GroupsRemoveUserFromGroupData = {
  body: GroupsRemoveUserFromGroupBody;
  path: {
    groupName: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupName}/users/remove";
};

export type GroupsRemoveUserFromGroupErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type GroupsRemoveUserFromGroupError = GroupsRemoveUserFromGroupErrors[keyof GroupsRemoveUserFromGroupErrors];

export type GroupsRemoveUserFromGroupResponses = {
  /**
   * A successful response.
   */
  200: GroupsRemoveUserFromGroupResponse;
};

export type GroupsRemoveUserFromGroupResponse2 =
  GroupsRemoveUserFromGroupResponses[keyof GroupsRemoveUserFromGroupResponses];

export type IntegrationsListIntegrationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/integrations";
};

export type IntegrationsListIntegrationsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type IntegrationsListIntegrationsError =
  IntegrationsListIntegrationsErrors[keyof IntegrationsListIntegrationsErrors];

export type IntegrationsListIntegrationsResponses = {
  /**
   * A successful response.
   */
  200: SuperplaneIntegrationsListIntegrationsResponse;
};

export type IntegrationsListIntegrationsResponse =
  IntegrationsListIntegrationsResponses[keyof IntegrationsListIntegrationsResponses];

export type OrganizationsAcceptInviteLinkData = {
  body?: never;
  path: {
    token: string;
  };
  query?: {
    id?: string;
    organizationId?: string;
    enabled?: boolean;
    createdAt?: string;
    updatedAt?: string;
  };
  url: "/api/v1/invite-links/{token}/accept";
};

export type OrganizationsAcceptInviteLinkErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsAcceptInviteLinkError =
  OrganizationsAcceptInviteLinkErrors[keyof OrganizationsAcceptInviteLinkErrors];

export type OrganizationsAcceptInviteLinkResponses = {
  /**
   * A successful response.
   */
  200: {
    [key: string]: unknown;
  };
};

export type OrganizationsAcceptInviteLinkResponse =
  OrganizationsAcceptInviteLinkResponses[keyof OrganizationsAcceptInviteLinkResponses];

export type MeMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/me";
};

export type MeMeErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type MeMeError = MeMeErrors[keyof MeMeErrors];

export type MeMeResponses = {
  /**
   * A successful response.
   */
  200: SuperplaneMeUser;
};

export type MeMeResponse = MeMeResponses[keyof MeMeResponses];

export type MeRegenerateTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/me/token";
};

export type MeRegenerateTokenErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type MeRegenerateTokenError = MeRegenerateTokenErrors[keyof MeRegenerateTokenErrors];

export type MeRegenerateTokenResponses = {
  /**
   * A successful response.
   */
  200: MeRegenerateTokenResponse;
};

export type MeRegenerateTokenResponse2 = MeRegenerateTokenResponses[keyof MeRegenerateTokenResponses];

export type OrganizationsDeleteOrganizationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}";
};

export type OrganizationsDeleteOrganizationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsDeleteOrganizationError =
  OrganizationsDeleteOrganizationErrors[keyof OrganizationsDeleteOrganizationErrors];

export type OrganizationsDeleteOrganizationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsDeleteOrganizationResponse;
};

export type OrganizationsDeleteOrganizationResponse2 =
  OrganizationsDeleteOrganizationResponses[keyof OrganizationsDeleteOrganizationResponses];

export type OrganizationsDescribeOrganizationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}";
};

export type OrganizationsDescribeOrganizationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsDescribeOrganizationError =
  OrganizationsDescribeOrganizationErrors[keyof OrganizationsDescribeOrganizationErrors];

export type OrganizationsDescribeOrganizationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsDescribeOrganizationResponse;
};

export type OrganizationsDescribeOrganizationResponse2 =
  OrganizationsDescribeOrganizationResponses[keyof OrganizationsDescribeOrganizationResponses];

export type OrganizationsUpdateOrganizationData = {
  body: OrganizationsUpdateOrganizationBody;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}";
};

export type OrganizationsUpdateOrganizationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsUpdateOrganizationError =
  OrganizationsUpdateOrganizationErrors[keyof OrganizationsUpdateOrganizationErrors];

export type OrganizationsUpdateOrganizationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsUpdateOrganizationResponse;
};

export type OrganizationsUpdateOrganizationResponse2 =
  OrganizationsUpdateOrganizationResponses[keyof OrganizationsUpdateOrganizationResponses];

export type OrganizationsListIntegrationsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/integrations";
};

export type OrganizationsListIntegrationsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsListIntegrationsError =
  OrganizationsListIntegrationsErrors[keyof OrganizationsListIntegrationsErrors];

export type OrganizationsListIntegrationsResponses = {
  /**
   * A successful response.
   */
  200: SuperplaneOrganizationsListIntegrationsResponse;
};

export type OrganizationsListIntegrationsResponse =
  OrganizationsListIntegrationsResponses[keyof OrganizationsListIntegrationsResponses];

export type OrganizationsCreateIntegrationData = {
  body: OrganizationsCreateIntegrationBody;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/integrations";
};

export type OrganizationsCreateIntegrationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsCreateIntegrationError =
  OrganizationsCreateIntegrationErrors[keyof OrganizationsCreateIntegrationErrors];

export type OrganizationsCreateIntegrationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsCreateIntegrationResponse;
};

export type OrganizationsCreateIntegrationResponse2 =
  OrganizationsCreateIntegrationResponses[keyof OrganizationsCreateIntegrationResponses];

export type OrganizationsDeleteIntegrationData = {
  body?: never;
  path: {
    id: string;
    integrationId: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/integrations/{integrationId}";
};

export type OrganizationsDeleteIntegrationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsDeleteIntegrationError =
  OrganizationsDeleteIntegrationErrors[keyof OrganizationsDeleteIntegrationErrors];

export type OrganizationsDeleteIntegrationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsDeleteIntegrationResponse;
};

export type OrganizationsDeleteIntegrationResponse2 =
  OrganizationsDeleteIntegrationResponses[keyof OrganizationsDeleteIntegrationResponses];

export type OrganizationsDescribeIntegrationData = {
  body?: never;
  path: {
    id: string;
    integrationId: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/integrations/{integrationId}";
};

export type OrganizationsDescribeIntegrationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsDescribeIntegrationError =
  OrganizationsDescribeIntegrationErrors[keyof OrganizationsDescribeIntegrationErrors];

export type OrganizationsDescribeIntegrationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsDescribeIntegrationResponse;
};

export type OrganizationsDescribeIntegrationResponse2 =
  OrganizationsDescribeIntegrationResponses[keyof OrganizationsDescribeIntegrationResponses];

export type OrganizationsUpdateIntegrationData = {
  body: OrganizationsUpdateIntegrationBody;
  path: {
    id: string;
    integrationId: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/integrations/{integrationId}";
};

export type OrganizationsUpdateIntegrationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsUpdateIntegrationError =
  OrganizationsUpdateIntegrationErrors[keyof OrganizationsUpdateIntegrationErrors];

export type OrganizationsUpdateIntegrationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsUpdateIntegrationResponse;
};

export type OrganizationsUpdateIntegrationResponse2 =
  OrganizationsUpdateIntegrationResponses[keyof OrganizationsUpdateIntegrationResponses];

export type OrganizationsListIntegrationResourcesData = {
  body?: never;
  path: {
    id: string;
    integrationId: string;
  };
  query?: {
    parameters?: string;
  };
  url: "/api/v1/organizations/{id}/integrations/{integrationId}/resources";
};

export type OrganizationsListIntegrationResourcesErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsListIntegrationResourcesError =
  OrganizationsListIntegrationResourcesErrors[keyof OrganizationsListIntegrationResourcesErrors];

export type OrganizationsListIntegrationResourcesResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsListIntegrationResourcesResponse;
};

export type OrganizationsListIntegrationResourcesResponse2 =
  OrganizationsListIntegrationResourcesResponses[keyof OrganizationsListIntegrationResourcesResponses];

export type OrganizationsListInvitationsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/invitations";
};

export type OrganizationsListInvitationsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsListInvitationsError =
  OrganizationsListInvitationsErrors[keyof OrganizationsListInvitationsErrors];

export type OrganizationsListInvitationsResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsListInvitationsResponse;
};

export type OrganizationsListInvitationsResponse2 =
  OrganizationsListInvitationsResponses[keyof OrganizationsListInvitationsResponses];

export type OrganizationsCreateInvitationData = {
  body: OrganizationsCreateInvitationBody;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/invitations";
};

export type OrganizationsCreateInvitationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsCreateInvitationError =
  OrganizationsCreateInvitationErrors[keyof OrganizationsCreateInvitationErrors];

export type OrganizationsCreateInvitationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsCreateInvitationResponse;
};

export type OrganizationsCreateInvitationResponse2 =
  OrganizationsCreateInvitationResponses[keyof OrganizationsCreateInvitationResponses];

export type OrganizationsRemoveInvitationData = {
  body?: never;
  path: {
    id: string;
    invitationId: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/invitations/{invitationId}";
};

export type OrganizationsRemoveInvitationErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsRemoveInvitationError =
  OrganizationsRemoveInvitationErrors[keyof OrganizationsRemoveInvitationErrors];

export type OrganizationsRemoveInvitationResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsRemoveInvitationResponse;
};

export type OrganizationsRemoveInvitationResponse2 =
  OrganizationsRemoveInvitationResponses[keyof OrganizationsRemoveInvitationResponses];

export type OrganizationsGetInviteLinkData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/invite-link";
};

export type OrganizationsGetInviteLinkErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsGetInviteLinkError = OrganizationsGetInviteLinkErrors[keyof OrganizationsGetInviteLinkErrors];

export type OrganizationsGetInviteLinkResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsGetInviteLinkResponse;
};

export type OrganizationsGetInviteLinkResponse2 =
  OrganizationsGetInviteLinkResponses[keyof OrganizationsGetInviteLinkResponses];

export type OrganizationsUpdateInviteLinkData = {
  body: OrganizationsUpdateInviteLinkBody;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/invite-link";
};

export type OrganizationsUpdateInviteLinkErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsUpdateInviteLinkError =
  OrganizationsUpdateInviteLinkErrors[keyof OrganizationsUpdateInviteLinkErrors];

export type OrganizationsUpdateInviteLinkResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsUpdateInviteLinkResponse;
};

export type OrganizationsUpdateInviteLinkResponse2 =
  OrganizationsUpdateInviteLinkResponses[keyof OrganizationsUpdateInviteLinkResponses];

export type OrganizationsResetInviteLinkData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/invite-link/reset";
};

export type OrganizationsResetInviteLinkErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsResetInviteLinkError =
  OrganizationsResetInviteLinkErrors[keyof OrganizationsResetInviteLinkErrors];

export type OrganizationsResetInviteLinkResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsResetInviteLinkResponse;
};

export type OrganizationsResetInviteLinkResponse2 =
  OrganizationsResetInviteLinkResponses[keyof OrganizationsResetInviteLinkResponses];

export type OrganizationsRemoveUserData = {
  body?: never;
  path: {
    id: string;
    userId: string;
  };
  query?: never;
  url: "/api/v1/organizations/{id}/users/{userId}";
};

export type OrganizationsRemoveUserErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type OrganizationsRemoveUserError = OrganizationsRemoveUserErrors[keyof OrganizationsRemoveUserErrors];

export type OrganizationsRemoveUserResponses = {
  /**
   * A successful response.
   */
  200: OrganizationsRemoveUserResponse;
};

export type OrganizationsRemoveUserResponse2 = OrganizationsRemoveUserResponses[keyof OrganizationsRemoveUserResponses];

export type RolesListRolesData = {
  body?: never;
  path?: never;
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/roles";
};

export type RolesListRolesErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type RolesListRolesError = RolesListRolesErrors[keyof RolesListRolesErrors];

export type RolesListRolesResponses = {
  /**
   * A successful response.
   */
  200: RolesListRolesResponse;
};

export type RolesListRolesResponse2 = RolesListRolesResponses[keyof RolesListRolesResponses];

export type RolesCreateRoleData = {
  body: RolesCreateRoleRequest;
  path?: never;
  query?: never;
  url: "/api/v1/roles";
};

export type RolesCreateRoleErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type RolesCreateRoleError = RolesCreateRoleErrors[keyof RolesCreateRoleErrors];

export type RolesCreateRoleResponses = {
  /**
   * A successful response.
   */
  200: RolesCreateRoleResponse;
};

export type RolesCreateRoleResponse2 = RolesCreateRoleResponses[keyof RolesCreateRoleResponses];

export type RolesDeleteRoleData = {
  body?: never;
  path: {
    roleName: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/roles/{roleName}";
};

export type RolesDeleteRoleErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type RolesDeleteRoleError = RolesDeleteRoleErrors[keyof RolesDeleteRoleErrors];

export type RolesDeleteRoleResponses = {
  /**
   * A successful response.
   */
  200: RolesDeleteRoleResponse;
};

export type RolesDeleteRoleResponse2 = RolesDeleteRoleResponses[keyof RolesDeleteRoleResponses];

export type RolesDescribeRoleData = {
  body?: never;
  path: {
    roleName: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/roles/{roleName}";
};

export type RolesDescribeRoleErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type RolesDescribeRoleError = RolesDescribeRoleErrors[keyof RolesDescribeRoleErrors];

export type RolesDescribeRoleResponses = {
  /**
   * A successful response.
   */
  200: RolesDescribeRoleResponse;
};

export type RolesDescribeRoleResponse2 = RolesDescribeRoleResponses[keyof RolesDescribeRoleResponses];

export type RolesUpdateRoleData = {
  body: RolesUpdateRoleBody;
  path: {
    roleName: string;
  };
  query?: never;
  url: "/api/v1/roles/{roleName}";
};

export type RolesUpdateRoleErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type RolesUpdateRoleError = RolesUpdateRoleErrors[keyof RolesUpdateRoleErrors];

export type RolesUpdateRoleResponses = {
  /**
   * A successful response.
   */
  200: RolesUpdateRoleResponse;
};

export type RolesUpdateRoleResponse2 = RolesUpdateRoleResponses[keyof RolesUpdateRoleResponses];

export type RolesAssignRoleData = {
  body: RolesAssignRoleBody;
  path: {
    roleName: string;
  };
  query?: never;
  url: "/api/v1/roles/{roleName}/users";
};

export type RolesAssignRoleErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type RolesAssignRoleError = RolesAssignRoleErrors[keyof RolesAssignRoleErrors];

export type RolesAssignRoleResponses = {
  /**
   * A successful response.
   */
  200: RolesAssignRoleResponse;
};

export type RolesAssignRoleResponse2 = RolesAssignRoleResponses[keyof RolesAssignRoleResponses];

export type SecretsListSecretsData = {
  body?: never;
  path?: never;
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/secrets";
};

export type SecretsListSecretsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type SecretsListSecretsError = SecretsListSecretsErrors[keyof SecretsListSecretsErrors];

export type SecretsListSecretsResponses = {
  /**
   * A successful response.
   */
  200: SecretsListSecretsResponse;
};

export type SecretsListSecretsResponse2 = SecretsListSecretsResponses[keyof SecretsListSecretsResponses];

export type SecretsCreateSecretData = {
  body: SecretsCreateSecretRequest;
  path?: never;
  query?: never;
  url: "/api/v1/secrets";
};

export type SecretsCreateSecretErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type SecretsCreateSecretError = SecretsCreateSecretErrors[keyof SecretsCreateSecretErrors];

export type SecretsCreateSecretResponses = {
  /**
   * A successful response.
   */
  200: SecretsCreateSecretResponse;
};

export type SecretsCreateSecretResponse2 = SecretsCreateSecretResponses[keyof SecretsCreateSecretResponses];

export type SecretsDeleteSecretData = {
  body?: never;
  path: {
    idOrName: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/secrets/{idOrName}";
};

export type SecretsDeleteSecretErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type SecretsDeleteSecretError = SecretsDeleteSecretErrors[keyof SecretsDeleteSecretErrors];

export type SecretsDeleteSecretResponses = {
  /**
   * A successful response.
   */
  200: SecretsDeleteSecretResponse;
};

export type SecretsDeleteSecretResponse2 = SecretsDeleteSecretResponses[keyof SecretsDeleteSecretResponses];

export type SecretsDescribeSecretData = {
  body?: never;
  path: {
    idOrName: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/secrets/{idOrName}";
};

export type SecretsDescribeSecretErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type SecretsDescribeSecretError = SecretsDescribeSecretErrors[keyof SecretsDescribeSecretErrors];

export type SecretsDescribeSecretResponses = {
  /**
   * A successful response.
   */
  200: SecretsDescribeSecretResponse;
};

export type SecretsDescribeSecretResponse2 = SecretsDescribeSecretResponses[keyof SecretsDescribeSecretResponses];

export type SecretsUpdateSecretData = {
  body: SecretsUpdateSecretBody;
  path: {
    idOrName: string;
  };
  query?: never;
  url: "/api/v1/secrets/{idOrName}";
};

export type SecretsUpdateSecretErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type SecretsUpdateSecretError = SecretsUpdateSecretErrors[keyof SecretsUpdateSecretErrors];

export type SecretsUpdateSecretResponses = {
  /**
   * A successful response.
   */
  200: SecretsUpdateSecretResponse;
};

export type SecretsUpdateSecretResponse2 = SecretsUpdateSecretResponses[keyof SecretsUpdateSecretResponses];

export type SecretsDeleteSecretKeyData = {
  body?: never;
  path: {
    idOrName: string;
    keyName: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/secrets/{idOrName}/keys/{keyName}";
};

export type SecretsDeleteSecretKeyErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type SecretsDeleteSecretKeyError = SecretsDeleteSecretKeyErrors[keyof SecretsDeleteSecretKeyErrors];

export type SecretsDeleteSecretKeyResponses = {
  /**
   * A successful response.
   */
  200: SecretsDeleteSecretKeyResponse;
};

export type SecretsDeleteSecretKeyResponse2 = SecretsDeleteSecretKeyResponses[keyof SecretsDeleteSecretKeyResponses];

export type SecretsSetSecretKeyData = {
  body: SecretsSetSecretKeyBody;
  path: {
    idOrName: string;
    keyName: string;
  };
  query?: never;
  url: "/api/v1/secrets/{idOrName}/keys/{keyName}";
};

export type SecretsSetSecretKeyErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type SecretsSetSecretKeyError = SecretsSetSecretKeyErrors[keyof SecretsSetSecretKeyErrors];

export type SecretsSetSecretKeyResponses = {
  /**
   * A successful response.
   */
  200: SecretsSetSecretKeyResponse;
};

export type SecretsSetSecretKeyResponse2 = SecretsSetSecretKeyResponses[keyof SecretsSetSecretKeyResponses];

export type SecretsUpdateSecretNameData = {
  body: SecretsUpdateSecretNameBody;
  path: {
    idOrName: string;
  };
  query?: never;
  url: "/api/v1/secrets/{idOrName}/name";
};

export type SecretsUpdateSecretNameErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type SecretsUpdateSecretNameError = SecretsUpdateSecretNameErrors[keyof SecretsUpdateSecretNameErrors];

export type SecretsUpdateSecretNameResponses = {
  /**
   * A successful response.
   */
  200: SecretsUpdateSecretNameResponse;
};

export type SecretsUpdateSecretNameResponse2 = SecretsUpdateSecretNameResponses[keyof SecretsUpdateSecretNameResponses];

export type ServiceAccountsListServiceAccountsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/service-accounts";
};

export type ServiceAccountsListServiceAccountsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ServiceAccountsListServiceAccountsError =
  ServiceAccountsListServiceAccountsErrors[keyof ServiceAccountsListServiceAccountsErrors];

export type ServiceAccountsListServiceAccountsResponses = {
  /**
   * A successful response.
   */
  200: ServiceAccountsListServiceAccountsResponse;
};

export type ServiceAccountsListServiceAccountsResponse2 =
  ServiceAccountsListServiceAccountsResponses[keyof ServiceAccountsListServiceAccountsResponses];

export type ServiceAccountsCreateServiceAccountData = {
  body: ServiceAccountsCreateServiceAccountRequest;
  path?: never;
  query?: never;
  url: "/api/v1/service-accounts";
};

export type ServiceAccountsCreateServiceAccountErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ServiceAccountsCreateServiceAccountError =
  ServiceAccountsCreateServiceAccountErrors[keyof ServiceAccountsCreateServiceAccountErrors];

export type ServiceAccountsCreateServiceAccountResponses = {
  /**
   * A successful response.
   */
  200: ServiceAccountsCreateServiceAccountResponse;
};

export type ServiceAccountsCreateServiceAccountResponse2 =
  ServiceAccountsCreateServiceAccountResponses[keyof ServiceAccountsCreateServiceAccountResponses];

export type ServiceAccountsDeleteServiceAccountData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/service-accounts/{id}";
};

export type ServiceAccountsDeleteServiceAccountErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ServiceAccountsDeleteServiceAccountError =
  ServiceAccountsDeleteServiceAccountErrors[keyof ServiceAccountsDeleteServiceAccountErrors];

export type ServiceAccountsDeleteServiceAccountResponses = {
  /**
   * A successful response.
   */
  200: ServiceAccountsDeleteServiceAccountResponse;
};

export type ServiceAccountsDeleteServiceAccountResponse2 =
  ServiceAccountsDeleteServiceAccountResponses[keyof ServiceAccountsDeleteServiceAccountResponses];

export type ServiceAccountsDescribeServiceAccountData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/service-accounts/{id}";
};

export type ServiceAccountsDescribeServiceAccountErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ServiceAccountsDescribeServiceAccountError =
  ServiceAccountsDescribeServiceAccountErrors[keyof ServiceAccountsDescribeServiceAccountErrors];

export type ServiceAccountsDescribeServiceAccountResponses = {
  /**
   * A successful response.
   */
  200: ServiceAccountsDescribeServiceAccountResponse;
};

export type ServiceAccountsDescribeServiceAccountResponse2 =
  ServiceAccountsDescribeServiceAccountResponses[keyof ServiceAccountsDescribeServiceAccountResponses];

export type ServiceAccountsUpdateServiceAccountData = {
  body: ServiceAccountsUpdateServiceAccountBody;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/service-accounts/{id}";
};

export type ServiceAccountsUpdateServiceAccountErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ServiceAccountsUpdateServiceAccountError =
  ServiceAccountsUpdateServiceAccountErrors[keyof ServiceAccountsUpdateServiceAccountErrors];

export type ServiceAccountsUpdateServiceAccountResponses = {
  /**
   * A successful response.
   */
  200: ServiceAccountsUpdateServiceAccountResponse;
};

export type ServiceAccountsUpdateServiceAccountResponse2 =
  ServiceAccountsUpdateServiceAccountResponses[keyof ServiceAccountsUpdateServiceAccountResponses];

export type ServiceAccountsRegenerateServiceAccountTokenData = {
  body: ServiceAccountsRegenerateServiceAccountTokenBody;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/service-accounts/{id}/token";
};

export type ServiceAccountsRegenerateServiceAccountTokenErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type ServiceAccountsRegenerateServiceAccountTokenError =
  ServiceAccountsRegenerateServiceAccountTokenErrors[keyof ServiceAccountsRegenerateServiceAccountTokenErrors];

export type ServiceAccountsRegenerateServiceAccountTokenResponses = {
  /**
   * A successful response.
   */
  200: ServiceAccountsRegenerateServiceAccountTokenResponse;
};

export type ServiceAccountsRegenerateServiceAccountTokenResponse2 =
  ServiceAccountsRegenerateServiceAccountTokenResponses[keyof ServiceAccountsRegenerateServiceAccountTokenResponses];

export type TriggersListTriggersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/triggers";
};

export type TriggersListTriggersErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type TriggersListTriggersError = TriggersListTriggersErrors[keyof TriggersListTriggersErrors];

export type TriggersListTriggersResponses = {
  /**
   * A successful response.
   */
  200: TriggersListTriggersResponse;
};

export type TriggersListTriggersResponse2 = TriggersListTriggersResponses[keyof TriggersListTriggersResponses];

export type TriggersDescribeTriggerData = {
  body?: never;
  path: {
    name: string;
  };
  query?: never;
  url: "/api/v1/triggers/{name}";
};

export type TriggersDescribeTriggerErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type TriggersDescribeTriggerError = TriggersDescribeTriggerErrors[keyof TriggersDescribeTriggerErrors];

export type TriggersDescribeTriggerResponses = {
  /**
   * A successful response.
   */
  200: TriggersDescribeTriggerResponse;
};

export type TriggersDescribeTriggerResponse2 = TriggersDescribeTriggerResponses[keyof TriggersDescribeTriggerResponses];

export type UsersListUsersData = {
  body?: never;
  path?: never;
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
    includeServiceAccounts?: boolean;
  };
  url: "/api/v1/users";
};

export type UsersListUsersErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type UsersListUsersError = UsersListUsersErrors[keyof UsersListUsersErrors];

export type UsersListUsersResponses = {
  /**
   * A successful response.
   */
  200: UsersListUsersResponse;
};

export type UsersListUsersResponse2 = UsersListUsersResponses[keyof UsersListUsersResponses];

export type UsersListUserPermissionsData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/users/{userId}/permissions";
};

export type UsersListUserPermissionsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type UsersListUserPermissionsError = UsersListUserPermissionsErrors[keyof UsersListUserPermissionsErrors];

export type UsersListUserPermissionsResponses = {
  /**
   * A successful response.
   */
  200: UsersListUserPermissionsResponse;
};

export type UsersListUserPermissionsResponse2 =
  UsersListUserPermissionsResponses[keyof UsersListUserPermissionsResponses];

export type UsersListUserRolesData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: {
    domainType?: "DOMAIN_TYPE_UNSPECIFIED" | "DOMAIN_TYPE_ORGANIZATION";
    domainId?: string;
  };
  url: "/api/v1/users/{userId}/roles";
};

export type UsersListUserRolesErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type UsersListUserRolesError = UsersListUserRolesErrors[keyof UsersListUserRolesErrors];

export type UsersListUserRolesResponses = {
  /**
   * A successful response.
   */
  200: UsersListUserRolesResponse;
};

export type UsersListUserRolesResponse2 = UsersListUserRolesResponses[keyof UsersListUserRolesResponses];

export type WidgetsListWidgetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/widgets";
};

export type WidgetsListWidgetsErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type WidgetsListWidgetsError = WidgetsListWidgetsErrors[keyof WidgetsListWidgetsErrors];

export type WidgetsListWidgetsResponses = {
  /**
   * A successful response.
   */
  200: WidgetsListWidgetsResponse;
};

export type WidgetsListWidgetsResponse2 = WidgetsListWidgetsResponses[keyof WidgetsListWidgetsResponses];

export type WidgetsDescribeWidgetData = {
  body?: never;
  path: {
    name: string;
  };
  query?: never;
  url: "/api/v1/widgets/{name}";
};

export type WidgetsDescribeWidgetErrors = {
  /**
   * An unexpected error response.
   */
  default: GooglerpcStatus;
};

export type WidgetsDescribeWidgetError = WidgetsDescribeWidgetErrors[keyof WidgetsDescribeWidgetErrors];

export type WidgetsDescribeWidgetResponses = {
  /**
   * A successful response.
   */
  200: WidgetsDescribeWidgetResponse;
};

export type WidgetsDescribeWidgetResponse2 = WidgetsDescribeWidgetResponses[keyof WidgetsDescribeWidgetResponses];
