/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ServiceAccountsUpdateServiceAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountsUpdateServiceAccountResponse{}

// ServiceAccountsUpdateServiceAccountResponse struct for ServiceAccountsUpdateServiceAccountResponse
type ServiceAccountsUpdateServiceAccountResponse struct {
	ServiceAccount *ServiceAccountsServiceAccount `json:"serviceAccount,omitempty"`
}

// NewServiceAccountsUpdateServiceAccountResponse instantiates a new ServiceAccountsUpdateServiceAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountsUpdateServiceAccountResponse() *ServiceAccountsUpdateServiceAccountResponse {
	this := ServiceAccountsUpdateServiceAccountResponse{}
	return &this
}

// NewServiceAccountsUpdateServiceAccountResponseWithDefaults instantiates a new ServiceAccountsUpdateServiceAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountsUpdateServiceAccountResponseWithDefaults() *ServiceAccountsUpdateServiceAccountResponse {
	this := ServiceAccountsUpdateServiceAccountResponse{}
	return &this
}

// GetServiceAccount returns the ServiceAccount field value if set, zero value otherwise.
func (o *ServiceAccountsUpdateServiceAccountResponse) GetServiceAccount() ServiceAccountsServiceAccount {
	if o == nil || IsNil(o.ServiceAccount) {
		var ret ServiceAccountsServiceAccount
		return ret
	}
	return *o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsUpdateServiceAccountResponse) GetServiceAccountOk() (*ServiceAccountsServiceAccount, bool) {
	if o == nil || IsNil(o.ServiceAccount) {
		return nil, false
	}
	return o.ServiceAccount, true
}

// HasServiceAccount returns a boolean if a field has been set.
func (o *ServiceAccountsUpdateServiceAccountResponse) HasServiceAccount() bool {
	if o != nil && !IsNil(o.ServiceAccount) {
		return true
	}

	return false
}

// SetServiceAccount gets a reference to the given ServiceAccountsServiceAccount and assigns it to the ServiceAccount field.
func (o *ServiceAccountsUpdateServiceAccountResponse) SetServiceAccount(v ServiceAccountsServiceAccount) {
	o.ServiceAccount = &v
}

func (o ServiceAccountsUpdateServiceAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountsUpdateServiceAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceAccount) {
		toSerialize["serviceAccount"] = o.ServiceAccount
	}
	return toSerialize, nil
}

type NullableServiceAccountsUpdateServiceAccountResponse struct {
	value *ServiceAccountsUpdateServiceAccountResponse
	isSet bool
}

func (v NullableServiceAccountsUpdateServiceAccountResponse) Get() *ServiceAccountsUpdateServiceAccountResponse {
	return v.value
}

func (v *NullableServiceAccountsUpdateServiceAccountResponse) Set(val *ServiceAccountsUpdateServiceAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountsUpdateServiceAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountsUpdateServiceAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountsUpdateServiceAccountResponse(val *ServiceAccountsUpdateServiceAccountResponse) *NullableServiceAccountsUpdateServiceAccountResponse {
	return &NullableServiceAccountsUpdateServiceAccountResponse{value: val, isSet: true}
}

func (v NullableServiceAccountsUpdateServiceAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountsUpdateServiceAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
