/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ServiceAccountsRegenerateServiceAccountTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountsRegenerateServiceAccountTokenResponse{}

// ServiceAccountsRegenerateServiceAccountTokenResponse struct for ServiceAccountsRegenerateServiceAccountTokenResponse
type ServiceAccountsRegenerateServiceAccountTokenResponse struct {
	Token *string `json:"token,omitempty"`
}

// NewServiceAccountsRegenerateServiceAccountTokenResponse instantiates a new ServiceAccountsRegenerateServiceAccountTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountsRegenerateServiceAccountTokenResponse() *ServiceAccountsRegenerateServiceAccountTokenResponse {
	this := ServiceAccountsRegenerateServiceAccountTokenResponse{}
	return &this
}

// NewServiceAccountsRegenerateServiceAccountTokenResponseWithDefaults instantiates a new ServiceAccountsRegenerateServiceAccountTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountsRegenerateServiceAccountTokenResponseWithDefaults() *ServiceAccountsRegenerateServiceAccountTokenResponse {
	this := ServiceAccountsRegenerateServiceAccountTokenResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *ServiceAccountsRegenerateServiceAccountTokenResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsRegenerateServiceAccountTokenResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *ServiceAccountsRegenerateServiceAccountTokenResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *ServiceAccountsRegenerateServiceAccountTokenResponse) SetToken(v string) {
	o.Token = &v
}

func (o ServiceAccountsRegenerateServiceAccountTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountsRegenerateServiceAccountTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableServiceAccountsRegenerateServiceAccountTokenResponse struct {
	value *ServiceAccountsRegenerateServiceAccountTokenResponse
	isSet bool
}

func (v NullableServiceAccountsRegenerateServiceAccountTokenResponse) Get() *ServiceAccountsRegenerateServiceAccountTokenResponse {
	return v.value
}

func (v *NullableServiceAccountsRegenerateServiceAccountTokenResponse) Set(val *ServiceAccountsRegenerateServiceAccountTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountsRegenerateServiceAccountTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountsRegenerateServiceAccountTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountsRegenerateServiceAccountTokenResponse(val *ServiceAccountsRegenerateServiceAccountTokenResponse) *NullableServiceAccountsRegenerateServiceAccountTokenResponse {
	return &NullableServiceAccountsRegenerateServiceAccountTokenResponse{value: val, isSet: true}
}

func (v NullableServiceAccountsRegenerateServiceAccountTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountsRegenerateServiceAccountTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
