/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ServiceAccountsCreateServiceAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountsCreateServiceAccountResponse{}

// ServiceAccountsCreateServiceAccountResponse struct for ServiceAccountsCreateServiceAccountResponse
type ServiceAccountsCreateServiceAccountResponse struct {
	ServiceAccount *ServiceAccountsServiceAccount `json:"serviceAccount,omitempty"`
	Token          *string                        `json:"token,omitempty"`
}

// NewServiceAccountsCreateServiceAccountResponse instantiates a new ServiceAccountsCreateServiceAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountsCreateServiceAccountResponse() *ServiceAccountsCreateServiceAccountResponse {
	this := ServiceAccountsCreateServiceAccountResponse{}
	return &this
}

// NewServiceAccountsCreateServiceAccountResponseWithDefaults instantiates a new ServiceAccountsCreateServiceAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountsCreateServiceAccountResponseWithDefaults() *ServiceAccountsCreateServiceAccountResponse {
	this := ServiceAccountsCreateServiceAccountResponse{}
	return &this
}

// GetServiceAccount returns the ServiceAccount field value if set, zero value otherwise.
func (o *ServiceAccountsCreateServiceAccountResponse) GetServiceAccount() ServiceAccountsServiceAccount {
	if o == nil || IsNil(o.ServiceAccount) {
		var ret ServiceAccountsServiceAccount
		return ret
	}
	return *o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsCreateServiceAccountResponse) GetServiceAccountOk() (*ServiceAccountsServiceAccount, bool) {
	if o == nil || IsNil(o.ServiceAccount) {
		return nil, false
	}
	return o.ServiceAccount, true
}

// HasServiceAccount returns a boolean if a field has been set.
func (o *ServiceAccountsCreateServiceAccountResponse) HasServiceAccount() bool {
	if o != nil && !IsNil(o.ServiceAccount) {
		return true
	}

	return false
}

// SetServiceAccount gets a reference to the given ServiceAccountsServiceAccount and assigns it to the ServiceAccount field.
func (o *ServiceAccountsCreateServiceAccountResponse) SetServiceAccount(v ServiceAccountsServiceAccount) {
	o.ServiceAccount = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *ServiceAccountsCreateServiceAccountResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsCreateServiceAccountResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *ServiceAccountsCreateServiceAccountResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *ServiceAccountsCreateServiceAccountResponse) SetToken(v string) {
	o.Token = &v
}

func (o ServiceAccountsCreateServiceAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountsCreateServiceAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceAccount) {
		toSerialize["serviceAccount"] = o.ServiceAccount
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableServiceAccountsCreateServiceAccountResponse struct {
	value *ServiceAccountsCreateServiceAccountResponse
	isSet bool
}

func (v NullableServiceAccountsCreateServiceAccountResponse) Get() *ServiceAccountsCreateServiceAccountResponse {
	return v.value
}

func (v *NullableServiceAccountsCreateServiceAccountResponse) Set(val *ServiceAccountsCreateServiceAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountsCreateServiceAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountsCreateServiceAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountsCreateServiceAccountResponse(val *ServiceAccountsCreateServiceAccountResponse) *NullableServiceAccountsCreateServiceAccountResponse {
	return &NullableServiceAccountsCreateServiceAccountResponse{value: val, isSet: true}
}

func (v NullableServiceAccountsCreateServiceAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountsCreateServiceAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
