/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ServiceAccountsUpdateServiceAccountBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountsUpdateServiceAccountBody{}

// ServiceAccountsUpdateServiceAccountBody struct for ServiceAccountsUpdateServiceAccountBody
type ServiceAccountsUpdateServiceAccountBody struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewServiceAccountsUpdateServiceAccountBody instantiates a new ServiceAccountsUpdateServiceAccountBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountsUpdateServiceAccountBody() *ServiceAccountsUpdateServiceAccountBody {
	this := ServiceAccountsUpdateServiceAccountBody{}
	return &this
}

// NewServiceAccountsUpdateServiceAccountBodyWithDefaults instantiates a new ServiceAccountsUpdateServiceAccountBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountsUpdateServiceAccountBodyWithDefaults() *ServiceAccountsUpdateServiceAccountBody {
	this := ServiceAccountsUpdateServiceAccountBody{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceAccountsUpdateServiceAccountBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsUpdateServiceAccountBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceAccountsUpdateServiceAccountBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceAccountsUpdateServiceAccountBody) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServiceAccountsUpdateServiceAccountBody) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsUpdateServiceAccountBody) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServiceAccountsUpdateServiceAccountBody) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServiceAccountsUpdateServiceAccountBody) SetDescription(v string) {
	o.Description = &v
}

func (o ServiceAccountsUpdateServiceAccountBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountsUpdateServiceAccountBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableServiceAccountsUpdateServiceAccountBody struct {
	value *ServiceAccountsUpdateServiceAccountBody
	isSet bool
}

func (v NullableServiceAccountsUpdateServiceAccountBody) Get() *ServiceAccountsUpdateServiceAccountBody {
	return v.value
}

func (v *NullableServiceAccountsUpdateServiceAccountBody) Set(val *ServiceAccountsUpdateServiceAccountBody) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountsUpdateServiceAccountBody) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountsUpdateServiceAccountBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountsUpdateServiceAccountBody(val *ServiceAccountsUpdateServiceAccountBody) *NullableServiceAccountsUpdateServiceAccountBody {
	return &NullableServiceAccountsUpdateServiceAccountBody{value: val, isSet: true}
}

func (v NullableServiceAccountsUpdateServiceAccountBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountsUpdateServiceAccountBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
