/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ServiceAccountsListServiceAccountsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountsListServiceAccountsResponse{}

// ServiceAccountsListServiceAccountsResponse struct for ServiceAccountsListServiceAccountsResponse
type ServiceAccountsListServiceAccountsResponse struct {
	ServiceAccounts []ServiceAccountsServiceAccount `json:"serviceAccounts,omitempty"`
}

// NewServiceAccountsListServiceAccountsResponse instantiates a new ServiceAccountsListServiceAccountsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountsListServiceAccountsResponse() *ServiceAccountsListServiceAccountsResponse {
	this := ServiceAccountsListServiceAccountsResponse{}
	return &this
}

// NewServiceAccountsListServiceAccountsResponseWithDefaults instantiates a new ServiceAccountsListServiceAccountsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountsListServiceAccountsResponseWithDefaults() *ServiceAccountsListServiceAccountsResponse {
	this := ServiceAccountsListServiceAccountsResponse{}
	return &this
}

// GetServiceAccounts returns the ServiceAccounts field value if set, zero value otherwise.
func (o *ServiceAccountsListServiceAccountsResponse) GetServiceAccounts() []ServiceAccountsServiceAccount {
	if o == nil || IsNil(o.ServiceAccounts) {
		var ret []ServiceAccountsServiceAccount
		return ret
	}
	return o.ServiceAccounts
}

// GetServiceAccountsOk returns a tuple with the ServiceAccounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsListServiceAccountsResponse) GetServiceAccountsOk() ([]ServiceAccountsServiceAccount, bool) {
	if o == nil || IsNil(o.ServiceAccounts) {
		return nil, false
	}
	return o.ServiceAccounts, true
}

// HasServiceAccounts returns a boolean if a field has been set.
func (o *ServiceAccountsListServiceAccountsResponse) HasServiceAccounts() bool {
	if o != nil && !IsNil(o.ServiceAccounts) {
		return true
	}

	return false
}

// SetServiceAccounts gets a reference to the given []ServiceAccountsServiceAccount and assigns it to the ServiceAccounts field.
func (o *ServiceAccountsListServiceAccountsResponse) SetServiceAccounts(v []ServiceAccountsServiceAccount) {
	o.ServiceAccounts = v
}

func (o ServiceAccountsListServiceAccountsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountsListServiceAccountsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceAccounts) {
		toSerialize["serviceAccounts"] = o.ServiceAccounts
	}
	return toSerialize, nil
}

type NullableServiceAccountsListServiceAccountsResponse struct {
	value *ServiceAccountsListServiceAccountsResponse
	isSet bool
}

func (v NullableServiceAccountsListServiceAccountsResponse) Get() *ServiceAccountsListServiceAccountsResponse {
	return v.value
}

func (v *NullableServiceAccountsListServiceAccountsResponse) Set(val *ServiceAccountsListServiceAccountsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountsListServiceAccountsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountsListServiceAccountsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountsListServiceAccountsResponse(val *ServiceAccountsListServiceAccountsResponse) *NullableServiceAccountsListServiceAccountsResponse {
	return &NullableServiceAccountsListServiceAccountsResponse{value: val, isSet: true}
}

func (v NullableServiceAccountsListServiceAccountsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountsListServiceAccountsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
