/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ServiceAccountsCreateServiceAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountsCreateServiceAccountRequest{}

// ServiceAccountsCreateServiceAccountRequest struct for ServiceAccountsCreateServiceAccountRequest
type ServiceAccountsCreateServiceAccountRequest struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Role        *string `json:"role,omitempty"`
}

// NewServiceAccountsCreateServiceAccountRequest instantiates a new ServiceAccountsCreateServiceAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountsCreateServiceAccountRequest() *ServiceAccountsCreateServiceAccountRequest {
	this := ServiceAccountsCreateServiceAccountRequest{}
	return &this
}

// NewServiceAccountsCreateServiceAccountRequestWithDefaults instantiates a new ServiceAccountsCreateServiceAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountsCreateServiceAccountRequestWithDefaults() *ServiceAccountsCreateServiceAccountRequest {
	this := ServiceAccountsCreateServiceAccountRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceAccountsCreateServiceAccountRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsCreateServiceAccountRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceAccountsCreateServiceAccountRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceAccountsCreateServiceAccountRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServiceAccountsCreateServiceAccountRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsCreateServiceAccountRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServiceAccountsCreateServiceAccountRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServiceAccountsCreateServiceAccountRequest) SetDescription(v string) {
	o.Description = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ServiceAccountsCreateServiceAccountRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsCreateServiceAccountRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ServiceAccountsCreateServiceAccountRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ServiceAccountsCreateServiceAccountRequest) SetRole(v string) {
	o.Role = &v
}

func (o ServiceAccountsCreateServiceAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountsCreateServiceAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableServiceAccountsCreateServiceAccountRequest struct {
	value *ServiceAccountsCreateServiceAccountRequest
	isSet bool
}

func (v NullableServiceAccountsCreateServiceAccountRequest) Get() *ServiceAccountsCreateServiceAccountRequest {
	return v.value
}

func (v *NullableServiceAccountsCreateServiceAccountRequest) Set(val *ServiceAccountsCreateServiceAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountsCreateServiceAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountsCreateServiceAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountsCreateServiceAccountRequest(val *ServiceAccountsCreateServiceAccountRequest) *NullableServiceAccountsCreateServiceAccountRequest {
	return &NullableServiceAccountsCreateServiceAccountRequest{value: val, isSet: true}
}

func (v NullableServiceAccountsCreateServiceAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountsCreateServiceAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
