/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ServiceAccountsDescribeServiceAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountsDescribeServiceAccountResponse{}

// ServiceAccountsDescribeServiceAccountResponse struct for ServiceAccountsDescribeServiceAccountResponse
type ServiceAccountsDescribeServiceAccountResponse struct {
	ServiceAccount *ServiceAccountsServiceAccount `json:"serviceAccount,omitempty"`
}

// NewServiceAccountsDescribeServiceAccountResponse instantiates a new ServiceAccountsDescribeServiceAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountsDescribeServiceAccountResponse() *ServiceAccountsDescribeServiceAccountResponse {
	this := ServiceAccountsDescribeServiceAccountResponse{}
	return &this
}

// NewServiceAccountsDescribeServiceAccountResponseWithDefaults instantiates a new ServiceAccountsDescribeServiceAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountsDescribeServiceAccountResponseWithDefaults() *ServiceAccountsDescribeServiceAccountResponse {
	this := ServiceAccountsDescribeServiceAccountResponse{}
	return &this
}

// GetServiceAccount returns the ServiceAccount field value if set, zero value otherwise.
func (o *ServiceAccountsDescribeServiceAccountResponse) GetServiceAccount() ServiceAccountsServiceAccount {
	if o == nil || IsNil(o.ServiceAccount) {
		var ret ServiceAccountsServiceAccount
		return ret
	}
	return *o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountsDescribeServiceAccountResponse) GetServiceAccountOk() (*ServiceAccountsServiceAccount, bool) {
	if o == nil || IsNil(o.ServiceAccount) {
		return nil, false
	}
	return o.ServiceAccount, true
}

// HasServiceAccount returns a boolean if a field has been set.
func (o *ServiceAccountsDescribeServiceAccountResponse) HasServiceAccount() bool {
	if o != nil && !IsNil(o.ServiceAccount) {
		return true
	}

	return false
}

// SetServiceAccount gets a reference to the given ServiceAccountsServiceAccount and assigns it to the ServiceAccount field.
func (o *ServiceAccountsDescribeServiceAccountResponse) SetServiceAccount(v ServiceAccountsServiceAccount) {
	o.ServiceAccount = &v
}

func (o ServiceAccountsDescribeServiceAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountsDescribeServiceAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceAccount) {
		toSerialize["serviceAccount"] = o.ServiceAccount
	}
	return toSerialize, nil
}

type NullableServiceAccountsDescribeServiceAccountResponse struct {
	value *ServiceAccountsDescribeServiceAccountResponse
	isSet bool
}

func (v NullableServiceAccountsDescribeServiceAccountResponse) Get() *ServiceAccountsDescribeServiceAccountResponse {
	return v.value
}

func (v *NullableServiceAccountsDescribeServiceAccountResponse) Set(val *ServiceAccountsDescribeServiceAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountsDescribeServiceAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountsDescribeServiceAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountsDescribeServiceAccountResponse(val *ServiceAccountsDescribeServiceAccountResponse) *NullableServiceAccountsDescribeServiceAccountResponse {
	return &NullableServiceAccountsDescribeServiceAccountResponse{value: val, isSet: true}
}

func (v NullableServiceAccountsDescribeServiceAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountsDescribeServiceAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
